# group pos_data Товары и услуги
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `



## Товары и услуги [/entity/assortment]
### Получить Товары и услуги [GET]
Запрос на получение товаров/модификаций и остатков по ним. Результат - список соответствующих сущностей
с информацией по их остаткам на складе. Если в настройках точки продаж установлено свойство **Выгружать только товары в наличии**,
то запрос вернет только товары и модификации с положительным остатком. Комплекты выгружаются все, вне зависимости от их остатка и значения свойства **Выгружать только товары в наличии**.

### Атрибуты ответа:
#### Общие для товаров, модификаций,услуг и комплектов
+ **meta** - Метаданные сущности `Необходимое`
+ **id** - id сущности ассортимента `Необходимое`
+ **syncId** - syncId товара/услуги/комплекта, уникальный внешний идентификатор
+ **name** - Наименование сущности `Необходимое`
+ **code** - Код сущности
+ **barcodes** - Массив штрихкодов сущности
+ **salePrices** - Массив цен продажи (объектов с полем **value**) сущности `Необходимое`
+ **productFolder** - Папка, в которой находится сущность. Для модификаций папка родительского товара.
+ **vat** - НДС (наследуется от папки при отсутствии)
___
#### Поля товаров
+ **article** - Артикул товара
+ **soldByWeight** - Весовой товар
+ **uom** - Единица измерения товара (строка)
+ **image** - Изображение товара (объект)
  - **href** - Ссылка на изображение
  - **miniature** - Ссылка на миниатюру изображения
  - **tiny** - Ссылка на уменьшенную версию изображения
+ **egaisIsAlcoholic** - признак «Алкогольная продукция» `Необходимое`
+ **egaisHasExciseMark** - признак «Содержит акцизную марку» `Необходимое`
+ **egaisProductCode** - код вида алкогольной продукции `Необходимое`
+ **egaisAlcoholPercent** - крепость алкогольной продукции `Необходимое`
+ **egaisVolume** - объем тары алкогольной продукции `Необходимое`
+ **stock** - Остаток `Необходимое`
+ **reserve**  - Резерв `Необходимое`
+ **isSerialtrackable** - учёт по серийным номерам `Необходимое`
+ **tobacco** - Табачная продукция. Не может быть указан вместе с **egaisIsAlcoholic**, **soldByWeight** и **isSerialtrackable**
+ **trackingType** - Тип маркируемой продукции
  + **NOT_TRACKED** - Без маркировки
  + **TOBACCO** - Тип маркировки "Табак"
  + **SHOES** - Тип маркировки "Обувь"
+ **tnved** - Код ТН ВЭД
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

+ **paymentItemType** - Признак предмета расчета
  + **GOOD** - Товар
  + **EXCISABLE_GOOD** - Подакцизный товар
  + **COMPOUND_PAYMENT_ITEM** - Составной предмет расчета
  + **ANOTHER_PAYMENT_ITEM** - Иной предмет расчета
+ **isDiscountProhibited** - Запретить скидки при продаже в розницу

+ **packs** - Массив упаковок
  + **id** - id сущности упаковки `Необходимое`
  + **name** - Название упаковки `Необходимое`
  + **quantity** - Количество товаров в упаковке `Необходимое`
  + **barcode** - Штрихкод упаковки
___
#### Поля модификаций
+ **characteristics** - Массив пар вида "`Наименование характеристики`:`значение`"
+ **product** - Основной товар
+ **isSerialtrackable** - учёт по серийным номерам `Необходимое`
___
#### Поля услуг
+ **uom** - Единица измерения услуги(строка)
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |
+ **paymentItemType** - Признак предмета расчета
  + **SERVICE** - Услуга
  + **WORK** - Работа
  + **PROVIDING_RID** - Предоставление РИД
  + **COMPOUND_PAYMENT_ITEM** - Составной предмет расчета
  + **ANOTHER_PAYMENT_ITEM** - Иной предмет расчета
+ **isDiscountProhibited** - Запретить скидки при продаже в розницу
___
#### Поля комплектов
+ **article** - Артикул комплекта
+ **uom** - Единица измерения комплекта (строка)
+ **vat** - НДС
+ **image** - Изображение товара (объект)
  - **href** - Ссылка на изображение
  - **miniature** - Ссылка на миниатюру изображения
  - **tiny** - Ссылка на уменьшенную версию изображения
+ **components** - Компоненты комплекта, это список товаров/услуг/модификаций, который входят в состав комплекта. Компонентов у комплекта может быть от 1 до 10. `Необходимое`
  - **meta** - Метаданные сущности `Необходимое`
  - **quantity** - количество компонентов в комплекте.
+ **trackingType** - Тип маркируемой продукции
  + **NOT_TRACKED** - Без маркировки
  + **TOBACCO** - Тип маркировки "Табак"
  + **SHOES** - Тип маркировки "Обувь"
+ **tnved** - Код ТН ВЭД
+ **paymentItemType** - Признак предмета расчета
  + **GOOD** - Товар
  + **EXCISABLE_GOOD** - Подакцизный товар
  + **COMPOUND_PAYMENT_ITEM** - Составной предмет расчета
  + **ANOTHER_PAYMENT_ITEM** - Иной предмет расчета
+ **isDiscountProhibited** - Запретить скидки при продаже в розницу
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

### Цены в рознице
Товары/услуги/комплекты в рознице отображаются со всеми типами цен (**salePrices**). Если тип цен не задан явно, то возвращается значение 0.
Модификации в рознице отображаются с явно проставленными типами цен (**salePrices**). Если тип цен не задан явно, то будет отображаться цена родительского товара.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление ассортимента товаров.
  + Body
        <!-- include(body/pos_assortment/get.json) -->
