# Group pos_data Настройки компании
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Настройки компании [/settings/companysettings]
### Получить Настройки компании [GET]
Запрос на получение Настроек компании.
### Атрибуты ответа:
+ **currency** - стандартная валюта `Необходимое`
  - **meta** - метаданные валюты `Необходимое`
  - **name** - наименование валюты `Необходимое`
  - **rate** - курс валюты `Необходимое`
  - **code** - код валюты `Необходимое`
+ **discountStrategy** - Cовместное применение скидок. Может принимать значения `[bySum, byPriority]` означающие "Сумма скидок" и "Приоритетная" соответственно. `Необходимое`
  - *"Сумма скидок"* `[bySum]` означает, что должна действовать сумма скидок
  - *"Приоритетная"* `[byPriority]` должна действовать одна, наиболее выгодная для покупателя скидка
+ **isWeightBarcodes** - Флаг, используются весовые штрихкоды `Необходимое`
+ **weightBarcodePrefix** - Строка, маска весовых штрихкодов `Необходимое`
+ **operationNumbering** - Нумерация документов. Может принимать значения `[GLOBAL, YEARLY]` означающие "Сквозная за всю историю" и "Внутри календарного года" соответственно. `Необходимое`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Настроек компании.
  + Body
        <!-- include(body/companysettings/get.json) -->
