# group pos_data Покупатели
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Покупатели [/entity/counterparty]
### Получить Покупателей [GET]
Запрос на получение списка всех контрагентов.

### Параметры запроса
+ **offsetId** - Смещение
+ **limit** - Максимальное возвращаемое кол-во
+ **direction** - Направление следующей страницы поиска
+ **search** - Строка для поиска. Возвращаемые контрагенты должны содержать соответствующую подстроку в одном из полей: name, email, phone, discountCardNumber

### Атрибуты ответа:
#### Служебные
+ **meta** - внешний уникальный идентификатор в формате метаданных (мета с syncId) `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
+ **syncId** - ID синхронизации
+ **version** - Версия сущности. Изменяется при обновлении/удалении Контрагента `Необходимое`
+ **updated** - Момент последнего обновления Контрагента `Необходимое`
+ **externalCode** - Внешний код Контрагента `Необходимое`
#### Основные данные
+ **name** - Имя Контрагента `Необходимое`
+ **code** - Код Контрагента
+ **description** - Описание Контрагента
+ **actualAddress** -Фактический адрес Контрагента
+ **tags** - Тэги (массив) `Необходимое`
#### Данные контрагента
+ **companyType** - Тип Контрагента. `Необходимое`
`[Юридическое лицо, Индивидуальный предприниматель, Физическое лицо]`.

| Тип контрагента                | Значение поля companyType  |
| ------------------------------ |:---------------------------|
| Юридическое лицо               | legal                      |
| Индивидуальный предприниматель | entrepreneur               |
| Физическое лицо                | individual                 |

+ **legalTitle** - Полное наименование Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН
+ **kpp** - КПП
+ **ogrn** - ОГРН
+ **ogrnip** - ОГРНИП
+ **okpo** - ОКПО
+ **certificateNumber** - Номер свидетельства
+ **certificateDate** - Дата свидетельства
#### Контактные данные
+ **email** - Адрес электронной почты
+ **phone** - Номер городского телефона
+ **fax** - Номер факса
#### Данные о скидках
+ **discounts** - Массив объектов-скидок, действующих на данного контрагента.
  - **discount** - Скидка
    * **meta** - метаданные скидки
    * **personalDiscount** - процент персональной скидки (если тип - персональная скидка)
    + **salesAmountCorrection** - Коррекция
+ **discountCardNumber** - Номер дисконтной карты
+ **salesAmount** - Сумма продаж контрагента `Необходимое`
+ **bonusProgram** - Метаданные активной бонусной программы
+ **bonusPoints** - Бонусные баллы по активной бонусной программе
+ **legalFirstName** - Имя контрагента
+ **legalMiddleName** - Отчество контрагента
+ **legalLastName** - Фамилия контрагента
+ **sex** - Пол контрагента
`[Мужской, Женский]`.

| Пол контрагента                | Значение поля sex          |
| ------------------------------ |:---------------------------|
| Мужской                        | MALE                       |
| Женский                        | FEMALE                     |

+ **birthDate** - Дата рождения контрагента

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка контрагентов.
  + Body
        <!-- include(body/pos_counterparty/get.json) -->


## Покупатели [/entity/counterparty/detail]

### Получить бонусные баллы Покупателя [POST]
Запрос на получение бонусных баллов контрагента. Необходимо передать объект, полученный из метода GET /entity/counterparty. Бонусные баллы возвращаются для каждого контрагента в отдельном запросе на получение баллов.

### Параметры запроса
+ **meta** - внешний уникальный идентификатор в формате метаданных (мета с syncId) `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
+ **syncId** - ID синхронизации
+ **version** - Версия сущности. Изменяется при обновлении/удалении Контрагента `Необходимое`
+ **updated** - Момент последнего обновления Контрагента `Необходимое`
+ **externalCode** - Внешний код Контрагента `Необходимое`
#### Основные данные
+ **name** - Имя Контрагента `Необходимое`
+ **code** - Код Контрагента
+ **description** - Описание Контрагента
+ **actualAddress** -Фактический адрес Контрагента
+ **tags** - Тэги (массив) `Необходимое`
#### Данные контрагента
+ **companyType** - Тип Контрагента. `Необходимое`
`[Юридическое лицо, Индивидуальный предприниматель, Физическое лицо]`.

| Тип контрагента                | Значение поля companyType  |
| ------------------------------ |:---------------------------|
| Юридическое лицо               | legal                      |
| Индивидуальный предприниматель | entrepreneur               |
| Физическое лицо                | individual                 |

+ **legalTitle** - Полное наименование Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН
+ **kpp** - КПП
+ **ogrn** - ОГРН
+ **ogrnip** - ОГРНИП
+ **okpo** - ОКПО
+ **certificateNumber** - Номер свидетельства
+ **certificateDate** - Дата свидетельства
#### Контактные данные
+ **email** - Адрес электронной почты
+ **phone** - Номер городского телефона
+ **fax** - Номер факса
#### Данные о скидках
+ **discounts** - Массив объектов-скидок, действующих на данного контрагента.
  - **discount** - Скидка
    * **meta** - метаданные скидки
    * **personalDiscount** - процент персональной скидки (если тип - персональная скидка)
    + **salesAmountCorrection** - Коррекция
+ **discountCardNumber** - Номер дисконтной карты
+ **salesAmount** - Сумма продаж контрагента `Необходимое`
+ **legalFirstName** - Имя контрагента
+ **legalMiddleName** - Отчество контрагента
+ **legalLastName** - Фамилия контрагента
+ **sex** - Пол контрагента
`[Мужской, Женский]`.

| Пол контрагента                | Значение поля sex          |
| ------------------------------ |:---------------------------|
| Мужской                        | MALE                       |
| Женский                        | FEMALE                     |

+ **birthDate** - Дата рождения контрагента



### Атрибуты ответа:
#### Служебные
+ **meta** - внешний уникальный идентификатор в формате метаданных (мета с syncId) `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
+ **syncId** - ID синхронизации
+ **version** - Версия сущности. Изменяется при обновлении/удалении Контрагента `Необходимое`
+ **updated** - Момент последнего обновления Контрагента `Необходимое`
+ **externalCode** - Внешний код Контрагента `Необходимое`
#### Основные данные
+ **name** - Имя Контрагента `Необходимое`
+ **code** - Код Контрагента
+ **description** - Описание Контрагента
+ **actualAddress** -Фактический адрес Контрагента
+ **tags** - Тэги (массив) `Необходимое`
#### Данные контрагента
+ **companyType** - Тип Контрагента. `Необходимое`
`[Юридическое лицо, Индивидуальный предприниматель, Физическое лицо]`.

| Тип контрагента                | Значение поля companyType  |
| ------------------------------ |:---------------------------|
| Юридическое лицо               | legal                      |
| Индивидуальный предприниматель | entrepreneur               |
| Физическое лицо                | individual                 |

+ **legalTitle** - Полное наименование Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН
+ **kpp** - КПП
+ **ogrn** - ОГРН
+ **ogrnip** - ОГРНИП
+ **okpo** - ОКПО
+ **certificateNumber** - Номер свидетельства
+ **certificateDate** - Дата свидетельства
#### Контактные данные
+ **email** - Адрес электронной почты
+ **phone** - Номер городского телефона
+ **fax** - Номер факса
#### Данные о скидках
+ **discounts** - Массив объектов-скидок, действующих на данного контрагента.
  - **discount** - Скидка
    * **meta** - метаданные скидки
    * **personalDiscount** - процент персональной скидки (если тип - персональная скидка)
    + **salesAmountCorrection** - Коррекция
+ **discountCardNumber** - Номер дисконтной карты
+ **salesAmount** - Сумма продаж контрагента `Необходимое`
+ **bonusProgram** - Метаданные активной бонусной программы
+ **bonusPoints** - Бонусные баллы по активной бонусной программе
+ **legalFirstName** - Имя контрагента
+ **legalMiddleName** - Отчество контрагента
+ **legalLastName** - Фамилия контрагента
+ **sex** - Пол контрагента
`[Мужской, Женский]`.

| Пол контрагента                | Значение поля sex          |
| ------------------------------ |:---------------------------|
| Мужской                        | MALE                       |
| Женский                        | FEMALE                     |

+ **birthDate** - Дата рождения контрагента

+ Request Пример (application/json)
Пример body запроса для получения информации по контрагенту.
  + Headers
      Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
      Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/pos_counterparty/get_id.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление данных контрагента.
  + Body
        <!-- include(body/pos_counterparty/get.json) -->
