# group pos_data Заказы покупателей
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Заказы покупателей [/entity/customerorder]
### Получить Заказы покупателей [GET]
Запрос на получение списка Заказов покупателей, соответствующих складу и организации точки продаж.
Не выгружаются Заказы с сериями, алкогольными товарами, непроведенные заказы, а также заказы без позиций и заказы, у которых более 1000 позиций.

### Атрибуты ответа:
#### Служебные
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
#### Основные данные
+ **name** - Имя `Необходимое`
+ **description** - Описание
+ **moment** - Дата `Необходимое`
+ **vatEnabled** - Учитывается ли НДС `Необходимое`
+ **vatIncluded** - Включен ли НДС в цену `Необходимое`
+ **deliveryPlannedMoment** - Планируемая дата отгрузки
+ **state** - Статус
+ **positions** - Ссылка на позиции в формате метаданных `Необходимое`
+ **agent** - Ссылка на покупателя в формате метаданных (Если заказ назначен на [стандартного розничный покупателя](#header-стандартный-розничный-покупатель), то это поле не придёт в составе заказа)
+ **paidInCash** - Оплачено наличными по заказу
+ **paidNoCash** - Оплачено картой по заказу
+ **paidByQr** - Оплачено по QR-коду по заказу
+ **shippedSum** - Отгружено
+ **prepayments** - Предоплаты связанные с заказом покупателя
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

### Позиции Заказа покупателя
Позиции Заказа - это список товаров/услуг/модификаций/комплектов.
Объект позиции Заказа содержит следующие поля:
+ **assortment** - Ссылка на товар/услугу/модификацию/комплект (мета), которую представляет собой позиция `Необходимое`
+ **quantity** - Количество товаров/услуг/модификаций/комплектов данного вида в позиции `Необходимое`
+ **price** - Цена товаров/услуг/модификаций/комплекта в копейках `Необходимое`
+ **vat** - НДС, которым облагается текущая позиция `Необходимое`
+ **discount** - Процент скидки или наценки `Необходимое`
+ **reserve** - Резерв данной позиции `Необходимое`
+ **pack** - Упаковка
  + **id** - id сущности упаковки `Необходимое`
  + **name** - Название упаковки `Необходимое`
  + **quantity** - Количество товаров в упаковке `Необходимое`
  + **barcode** - Штрихкод упаковки
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

### Статус Заказа покупателя
Объект статуса Заказа содержит следующие поля:
+ **name** - Наименование `Необходимое`
+ **color** - Цвет в цветовом пространстве ARGB `Необходимое`
+ **type** - Тип. Возможные значения: [`Regular`(обычный), `Successful`(Финальный положительный), `Unsuccessful`(Финальный отрицательный)] `Необходимое`

### Покупатель Заказа покупателя
Объект покупателя Заказа содержит следующие поля:
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **name** - Имя `Необходимое`

### Предоплаты Заказа покупателя
Объект предоплаты Заказа содержит следующие поля:
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **name** - Имя `Необходимое`

### Настройки, влияющие на выдачу заказов:
У точки продаж в основном приложении есть настройка: "Выгружать только заказы со статусами", которая влияет на выдачу заказов.
Если в этой настройке указаны статусы, то, при запросе заказов, будут возвращены только заказы с указанными статусами. Если статусы не указаны, будут выгружаться заказы со всеми статусами в т.ч. пустыми.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Заказов покупателей.
  + Body
        <!-- include(body/pos_customerorder/get.json) -->

# Заказы покупателей [/entity/customerorder/{id}]
### Получить Заказ покупателя [GET]
Запрос на получение заказа для точки продаж.

### Атрибуты ответа:
#### Служебные
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
#### Основные данные
+ **name** - Имя `Необходимое`
+ **description** - Описание
+ **moment** - Дата `Необходимое`
+ **vatEnabled** - Учитывается ли НДС `Необходимое`
+ **vatIncluded** - Включен ли НДС в цену `Необходимое`
+ **deliveryPlannedMoment** - Планируемая дата отгрузки
+ **state** - Статус
+ **positions** - Ссылка на позиции в формате метаданных `Необходимое`
+ **agent** - Ссылка на покупателя в формате метаданных (Если заказ назначен на [стандартного розничный покупателя](#header-стандартный-розничный-покупатель), то это поле не придёт в составе заказа)
+ **paidInCash** - Оплачено наличными по заказу
+ **paidNoCash** - Оплачено картой по заказу
+ **paidByQr** - Оплачено по QR-коду по заказу
+ **shippedSum** - Отгружено
+ **prepayments** - Предоплаты связанные с заказом покупателя
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

### Позиции Заказа покупателя
Позиции Заказа - это список товаров/услуг/модификаций/комплектов.
Объект позиции Заказа содержит следующие поля:
+ **assortment** - Ссылка на товар/услугу/модификацию/комплект (мета), которую представляет собой позиция `Необходимое`
+ **quantity** - Количество товаров/услуг/модификаций/комплектов данного вида в позиции `Необходимое`
+ **price** - Цена товаров/услуг/модификаций/комплекта в копейках `Необходимое`
+ **vat** - НДС, которым облагается текущая позиция `Необходимое`
+ **discount** - Процент скидки или наценки `Необходимое`
+ **reserve** - Резерв данной позиции `Необходимое`
+ **pack** - Упаковка
  + **id** - id сущности упаковки `Необходимое`
  + **name** - Название упаковки `Необходимое`
  + **quantity** - Количество товаров в упаковке `Необходимое`
  + **barcode** - Штрихкод упаковки
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

### Статус Заказа покупателя
Объект статуса Заказа содержит следующие поля:
+ **name** - Наименование `Необходимое`
+ **color** - Цвет в цветовом пространстве ARGB `Необходимое`
+ **type** - Тип. Возможные значения: [`Regular`(обычный), `Successful`(Финальный положительный), `Unsuccessful`(Финальный отрицательный)] `Необходимое`

### Покупатель Заказа покупателя
Объект покупателя Заказа содержит следующие поля:
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **name** - Имя `Необходимое`

### Предоплаты Заказа покупателя
Объект предоплаты Заказа содержит следующие поля:
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **name** - Имя `Необходимое`

### Настройки, влияющие на выдачу заказов:
У точки продаж в основном приложении есть настройка: "Выгружать только заказы со статусами", которая влияет на выдачу заказов.
Если в этой настройке указаны статусы, то, при запросе заказов, будут возвращены только заказы с указанными статусами. Если статусы не указаны, будут выгружаться заказы со всеми статусами в т.ч. пустыми.

+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Заказа покупателя

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Заказов покупателей.
  + Body
        <!-- include(body/pos_customerorder/get_by_id.json) -->

## Заказы покупателей [/entity/customerorder]

### Создать заказ покупателя [POST]
Запрос на создание нового заказа покупателя.

Обязательные поля для создания заказа:
+ **meta** - Метаданные
+ **agent** - Ссылка на контрагента.

В случае, если не будет передано поле **name** - оно будет автоматически присвоено на сервере.
После создания, заказу будет выставлена Организация, указанная в настройках точки продаж.

<h2> Атрибуты запроса </h2>
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

+ Request Пример 1 (application/json)
Пример создания нового заказа покупателя.
  + Headers
    Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
    Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/pos_customerorder/post_request.json) -->

+ Response 201
  + Body
        <!-- include(body/pos_customerorder/post_response.json) -->