# group pos_data Скидки
Перед работой со скидками настоятельно рекомендуем вам прочитать [вот эту статью](https://support.moysklad.ru/hc/ru/articles/203392253-%D0%A1%D0%BA%D0%B8%D0%B4%D0%BA%D0%B8) на портале поддержки МоегоСклада.

### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Скидки [/entity/discount]

### Получить все скидки [GET]
Запрос на получение всех скидок учётной записи.
## Атрибуты ответа
### Общие поля
+ **meta** - Метаданные `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
+ **name** - Наименование скидки `Необходимое`
+ **agentTags** - Тэги контрагентов, к которым применяется скидка, если применяется не ко всем контрагентам
+ **allProducts**  - Все товары и услуги. Если этот флаг выставлен true, то коллекции **assortment** и **productFolders** будут отсутствовать в составе объекта.  `Необходимое`
+ **assortment** - Товары и услуги, которые были выбраны для применения скидки, если та применяется не ко всем товарам
  - **meta** - [метаданные](#header-метаданные) товара или услуги
_____
### Поля Спец. цен
+ **productFolders** - Товары и папки, к которым применяется скидка, если применяется не ко всем товарам
  - **meta** - [метаданные](#header-метаданные) папки
  - **productFolder** - ссылка на родительскую папку
  - **id** - id папки
  - **name** - наименование папки
  - **namepath** - путь к данной папке, состоящий из имён родительских папок
  - **path** - путь к данной папке, состоящий из id родительских папок
+ **discount** - Процент скидки если выбран фиксированный процент
+ **specialPrice** - Спец. цена (если выбран тип цен)
  - **priceType** - Наименование типа цены
____
### Поля накопительных скидок
+ **productFolders** - Товары и папки, к которым применяется скидка, если применяется не ко всем товарам
  - **meta** - [метаданные](#header-метаданные) папки
  - **productFolder** - ссылка на родительскую папку
  - **id** - id папки
  - **name** - наименование папки
  - **namepath** - путь к данной папке, состоящий из имён родительских папок
  - **path** - путь к данной папке, состоящий из id родительских папок
+ **levels** - проценты скидок при определённой сумме продаж  `Необходимое`
  - **amount** - Сумма накоплений в рублях
  - **discount** - Процент скидки, соответствующий данной сумме

+ Response 200 (application/json)
Успешный запрос. Результат - список всех скидок всех типов на учетной записи.
  + Body
        <!-- include(body/pos_discount/get.json) -->
