# group Скидки
Перед работой со скидками настоятельно рекомендуем вам прочитать [вот эту статью](https://support.moysklad.ru/hc/ru/articles/203392253-%D0%A1%D0%BA%D0%B8%D0%B4%D0%BA%D0%B8) на портале поддержки МоегоСклада.

## Настройки скидок
Найстройки скидок представляют собой отдельное поле в настройках компании. Это поле - **discountStrategy** строкового типа. Может принимать значения:
+ *bySum* - Совместное применение скидок = Сумма скидок
+ *byPriority* - Совместное применение скидок = Приоритетная

## Контрагенты
После создания скидок, контрагенты к которым, применяется данная скидка получают дополнительный объект *discount* в поле **discounts** являющийся связью конкретного
контрагента с данной скидкой, если у данной скидки указана не нулевая корректировка. 

## Скидки [/entity/discount]
## Атрибуты сущности
+ **meta** - Метаданные
+ **id** - ID в формате UUID
+ **accountId** - ID учётной записи
+ **name** - Наименование скидки
+ **active** - Флажок о том, действует ли скидка
+ **agentTags** - Тэги контрагентов, к которым применяется скидка, если применяется не ко всем контрагентам
+ **goodfolders** - Товары и папки, к которым применяется скидка, если применяется не ко всем товарам
+ **features** - Модификации, которые были выбраны для применения скидки, если та применяется не ко всем товарам

### Получить все скидки [GET]
Запрос на получение абсолютно всех скидок на учётной записи.
+ Response 200 (application/json)
Успешный запрос. Результат - список всех скидок всех типов на учетной записи.
  + Body
        <!-- include(body/pos_discount/get.json) -->

## Специальные цены [/entity/specialpricediscount]
## Атрибуты сущности
+ **meta** - Метаданные
+ **id** - ID в формате UUID
+ **accountId** - ID учётной записи
+ **name** - Наименование скидки
+ **active** - Флажок о том, действует ли скидка
+ **agentTags** - Тэги контрагентов, к которым применяется скидка, если применяется не ко всем контрагентам
+ **goodfolders** - Товары и папки, к которым применяется скидка, если применяется не ко всем товарам
+ **features** - Модификации, которые были выбраны для применения скидки, если та применяется не ко всем товарам
+ **discount** - Процент скидки если выбран фиксированный процент
+ **specialPrice** - Спец. цена (если выбрана)

## Специальная цена
поле **specialPrice** - объект, по своей структуре идентичный с типом цен. Поля:
**value** - Значение цены
**priceType** - Наименование типа цены

### Получить все спец. цены [GET]
Запрос на получение всех скидок типа "Специальная цена".
+ Response 200 (application/json)
Успешный запрос. Результ - список всех "Специальных цен" на учётной записи.
  + Body
        <!-- include(body/pos_discount/special/get.json) -->

## Специальная цена [/entity/specialpricediscount/{id}]
Ресурс для доступа к отдельной специальной цене.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Специальной цены
### Получить спец. цену [GET]
Запрос на получение специальной цены с указанным в качестве URI параметра id этой цены.
+ Response 200 (application/json)
Успешный запрос. Результат - специальная цена с указанным id.
  + Body
        <!-- include(body/pos_discount/special/get_by_id.json) -->

## Накопительные скидки [/entity/accumulationdiscount]
## Атрибуты сущности
+ **meta** - Метаданные
+ **id** - ID в формате UUID
+ **accountId** - ID учётной записи
+ **name** - Наименование скидки
+ **active** - Флажок о том, действует ли скидка
+ **agentTags** - Тэги контрагентов, к которым применяется скидка, если применяется не ко всем контрагентам
+ **goodfolders** - Товары и папки, к которым применяется скидка, если применяется не ко всем товарам
+ **features** - Модификации, которые были выбраны для применения скидки, если та применяется не ко всем товарам
+ **levels** - Условия скидки

## Условия
поле **levels** - массив объектов, представляющих собой условия накопительной скидки. Объекты состоят из 2х полей:
+ **amount** - Сумма накоплений в рублях
+ **discount** - Процент скидки, соответствующий данной сумме

### Получить все накопительные скидки [GET]
Запрос на получение всех скидок типа "Накопительная скидка" на учётной записи.
+ Response 200 (application/json)
Успешный запрос. Результат - список всех накопительных скидок.
  + Body
        <!-- include(body/pos_discount/accumulative/get.json) -->

## Накопительная скидка [/entity/accumulationdiscount/{id}]
Ресурс для доступа к отдельной накопительной скидке.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Накопительной скидки
### Получить накопительную скидку [GET]
Запрос на получение отдельной накопительной скидки с id переданным в качестве URI параметра.
+ Response 200 (application/json)
Успешный запрос. Результат - накопительная скидка с переданным id.
  + Body
        <!-- include(body/pos_discount/accumulative/get_by_id.json) -->

## Персональные скидки [/entity/personaldiscount]
## Атрибуты сущности
+ **meta** - Метаданные
+ **id** - ID в формате UUID
+ **accountId** - ID учётной записи
+ **name** - Наименование скидки
+ **active** - Флажок о том, действует ли скидка
+ **agentTags** - Тэги контрагентов, к которым применяется скидка, если применяется не ко всем контрагентам
+ **goodfolders** - Товары и папки, к которым применяется скидка, если применяется не ко всем товарам
+ **features** - Модификации, которые были выбраны для применения скидки, если та применяется не ко всем товарам

### Получить все персональные скидки [GET]
Запрос на получение всех скидок типа "Персональная скидка" на учётной записи.
+ Response 200 (application/json)
Успешный запрос. Результат - список всех персональных скидок.
  + Body
        <!-- include(body/pos_discount/personal/get.json) -->

## Персональная скидка [/entity/personaldiscount/{id}]
Ресурс для доступа к отдельной персональной скидке.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Персональной скидки
### Получить персональную скидку [GET]
Запрос на получение отдельной персональной скидки с id, переданным в качестве URI параметра.
+ Response 200 (application/json)
Успешный запрос. Результат - персональная скидка с переданным id.
  + Body
        <!-- include(body/pos_discount/personal/get_by_id.json) -->
