<h3><a name="обработка-ошибок-1000"></a>1000</h3>
+ **Сообщение**: *Элемент URI не является идентификатором*
+ **Описание**: Вероятнее всего вы пытаетесь обратиться к несуществующему ресурсу. Проверьте
  указанный вами URI, проверьте правильно ли вы указали ключевое слово сущности и полностью ли вы скопировали ID.

<h3><a name="обработка-ошибок-1002"></a>1002</h3>
+ **Сообщение**: *Неопознанный путь: {путь}*
+ **Описание**: Не удалось определить ресурс, по которому был сделан запрос. Проверьте URI, по которому совершается запрос.

<h3><a name="обработка-ошибок-1004"></a>1004</h3>
+ **Сообщение**: *Ошибка при формировании результата: {текст ошибки}*
+ **Описание**: При разборе переданного объекта произошла ошибка. Проверьте корректность переданных данных.

<h3><a name="обработка-ошибок-1005"></a>1005</h3>
+ **Сообщение**: *Неизвестный тип: {тип}*
+ **Описание**: Тип сущности, указанный в URI, не может быть найден. Проверьте корректность ключевого слова.

<h3><a name="обработка-ошибок-1007"></a>1007</h3>
+ **Сообщение**: *Неизвестное поле: {имя поля}*
+ **Описание**: При обновлении сущности указанное поле не было найдено. Проверьте правильность написания имени поля, а также убедитесь что данное поле присутствует среди атрибутов сущностей этого типа.

<h3><a name="обработка-ошибок-1008"></a>1008</h3>
+ **Сообщение**: *Ошибка при загрузке объекта с типом '{тип}' и идентификатором '{id}'*
+ **Описание**:  Не удалось загрузить сущность с данным id. Проверьте корректность id. Убедитесь что сущность с данным id присутствует среди списка сущностей данного типа (возможно сущность с данным id была удалена).

<h3><a name="обработка-ошибок-1009"></a>1009</h3>
+ **Сообщение**: *Редактирование объектов типа '{тип}' не поддерживается*
+ **Описание**: Сущность которую вы пытаетесь обновить - readonly. Изменение её атрибутов не предусмотрено.

<h3><a name="обработка-ошибок-1010"></a>1010</h3>
+ **Сообщение**: *Удаление объектов типа '{тип}' не поддерживается*
+ **Описание**: Нельзя удалить сущность данного типа. Проверьте есть ли среди операций данного типа сущностей операция удаления.

<h3><a name="обработка-ошибок-1011"></a>1011</h3>
+ **Сообщение**: *Создание объектов типа '{тип}' не поддерживается*
+ **Описание**: Нельзя создать сущность данного типа. Проверьте есть ли среди операций данного типа сущностей операция создания.

<h3><a name="обработка-ошибок-1012"></a>1012</h3>
+ **Сообщение**: *Не указан идентификатор объекта*
+ **Описание**: Ресурс, к которому вы обратились, требует идентификатор объекта.

<h3><a name="обработка-ошибок-1014"></a>1014</h3>
+ **Сообщение**: *Неверное значение '{значение}' параметра фильтрации '{имя параметра}'*
+ **Описание**: Вы указали значение неподдерживаемого типа для данного параметра (например передали int вместо boolean). Возможно ошибка в неправильном формате даты и времени.

<h3><a name="обработка-ошибок-1015"></a>1015</h3>
+ **Сообщение**: *Указана неверная версия в url: {url}*
+ **Описание**: Проверьте необходимую версию API в url по которому вы делаете запрос. `online.moysklad.ru/api/1.x/...` Версии API различаются между собой по количеству
доступных ресурсов, а также по способу обработки данных и именно поэтому являются важным элементом идентификации того или иного ресурса.

<h3><a name="обработка-ошибок-1016"></a>1016</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на просмотр данного объекта*
+ **Описание**: Администратор учётной записи ограничил ваши права на просмотр сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1017"></a>1017</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на редактирование данного объекта*
+ **Описание**: Администратор учётной записи ограничил ваши права на редактирование сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1019"></a>1019</h3>
+ **Сообщение**: *Чтение поля '{имя поля}' не поддерживается*
+ **Описание**: Невозможно чтение поля данного типа.

<h3><a name="обработка-ошибок-1020"></a>1020</h3>
+ **Сообщение**: *Родительский объект с типом '{тип}' и идентификатором '{id}' не существует*
+ **Описание**: Неверный id родительской сущности.

<h3><a name="обработка-ошибок-1021"></a>1021</h3>
+ **Сообщение**: *Объект с типом '{тип}' и идентификатором '{id}' не найден*
+ **Описание**: Не удалось загрузить сущность данного типа с данным id. Проверьте корректность id. Убедитесь что сущность с данным id присутствует среди списка сущностей данного типа (возможно сущность с данным id была удалена)

<h3><a name="обработка-ошибок-1022"></a>1022</h3>
+ **Сообщение**: *Ошибка при создании объекта*
+ **Описание**: Ошибка в процессе создания сущности данного типа.

<h3><a name="обработка-ошибок-1023"></a>1023</h3>
+ **Сообщение**: *Ошибка сохранения объекта: дочерний объект с типом '{тип}' и идентификатором '{id}' уже используется и не может быть удален*
+ **Описание**: Невозможно удалить объект во вложенной коллекции т.к. он уже где-то используется. Например, может возникнуть при удалении позиции из документа, по которому есть возврат,
в котором присутствует данная позиция.

<h3><a name="обработка-ошибок-1024"></a>1024</h3>
+ **Сообщение**: *Ошибка сохранения объекта: изменять стандартные объекты запрещено*
+ **Описание**: Вы пытаетесь изменить сущность, которая создаётся по умолчанию в сервисе МойСклад сразу после регистрации учётной записи. Это делать запрещено. (Например изменение стандартных стран и единиц измерения)

<h3><a name="обработка-ошибок-1027"></a>1027</h3>
+ **Сообщение**: *Запрос не содержит объектов*
+ **Описание**: Body запросов на создание/обновление должно представляться в виде объекта либо массива JSON.

<h3><a name="обработка-ошибок-1034"></a>1034</h3>
+ **Сообщение**: *Ошибка фильтрации: {текст ошибки}*
+ **Описание**: Ошибка в процессе обработки фильтров. Проверьте переданные фильтры на валидность. Подробнее о параметрах фильтрации вы можете прочесть в соответствующем разделе документации или в документации по сущности, к которой вы пытаетесь применять фильтры.

<h3><a name="обработка-ошибок-1035"></a>1035</h3>
+ **Сообщение**: *Ошибка фильтрации: неверный формат даты параметра фильтрации*
+ **Описание**: Проверьте значение даты и времени. Оно должно соответствовать формату `yyyy-MM-dd HH:mm:ss`

<h3><a name="обработка-ошибок-1036"></a>1036</h3>
+ **Сообщение**: *Ошибка при формировании метаданных*
+ **Описание** Внутренняя ошибка сервиса. Попробуйте повторить запрос.

<h3><a name="обработка-ошибок-1038"></a>1038</h3>
+ **Сообщение**: *Ошибка в адресе запроса*
+ **Описание** Проверьте, указываете ли вы валидный адрес запроса.

<h3><a name="обработка-ошибок-1039"></a>1039</h3>
+ **Сообщение**: *Операция {HTTP метод} не поддерживается для данного ресурса*
+ **Описание** Проверьте метод, с которым вы обращаетесь к ресурсу. Убедитесь, что в документации ресурса этот метод описан и его можно применить.

<h3><a name="обработка-ошибок-1040"></a>1040</h3>
+ **Сообщение**: *Неверно заданы параметры запроса*
+ **Описание** Один или несколько параметров запроса заданы некорректно. Проверьте формат параметров согласно документации.

<h3><a name="обработка-ошибок-1044"></a>1044</h3>
+ **Сообщение**: *Превышен максимальный размер запроса*
+ **Описание**: Максимальный размер запроса 10 МБ.

<h3><a name="обработка-ошибок-1048"></a>1048</h3>
+ **Сообщение**: *Превышено ограничение на количество попыток проверки имени и пароля*
+ **Описание** Вы попытались авторизоваться с помощью пары логин-пароль слишком много раз.

<h3><a name="обработка-ошибок-1049"></a>1049</h3>
+ **Сообщение**: *Превышено ограничение на количество запросов в единицу времени*
+ **Описание** От вас поступает слишком много запросов в единицу времени.

<h3><a name="обработка-ошибок-1050"></a>1050</h3>
+ **Сообщение**: *Запрос метаданных не поддерживается в posap*
+ **Описание** В posap не поддерживаются запросы на получение метаданных.

<h3><a name="обработка-ошибок-1051"></a>1051</h3>
+ **Сообщение**: *Тип <type> не совпадает с типом <meta_type> из meta*
+ **Описание** Тип, который вы указали в объекте **meta** не соответствует типу ресурса, к которому вы делаете запрос.

<h3><a name="обработка-ошибок-1052"></a>1052</h3>
+ **Сообщение**: *Неверный формат UUID*
+ **Описание**: Проверьте сгенерированные вами UUID на корректность.

<h3><a name="обработка-ошибок-1053"></a>1053</h3>
+ **Сообщение**: *Чтение объектов типа '{тип}' не поддерживается*
+ **Описание**: Нельзя прочтитать сущность данного типа.

<h3><a name="обработка-ошибок-1054"></a>1054</h3>
+ **Сообщение**: *Указанный тип {тип сущности} не найден*
+ **Описание** Ресурс для переданного типа не существует.

<h3><a name="обработка-ошибок-1055"></a>1055</h3>
+ **Сообщение**: *Неизвестное значение {значение} параметра direction*
+ **Описание** Вы передали некорректное значение **direction**. Можно передать только одно из следующих значений: `forward, backward`.

<h3><a name="обработка-ошибок-1056"></a>1056</h3>
+ **Сообщение**: *Ошибка аутентификации: {текст ошибки аутентификации}*
+ **Описание** Проверьте указанные для аутентификации данные. Возможно для данного ресурса требуется другой вид аутентификации.

<h3><a name="обработка-ошибок-1057"></a>1057</h3>
+ **Сообщение**: *Отсутствует syncid для сущности*
+ **Описание** В posap в ссылках (**href**) в **meta** необходимо всегда указывать /syncId/{id} сущности, который должен генерироваться на клиенте.

<h3><a name="обработка-ошибок-1060"></a>1060</h3>
+ **Сообщение**: *Некорректный тип данных в meta сущности, поле type*
+ **Описание** Тип данных указанный в поле type метаданных сущности не совпадает с ожидаемым типом.

<h3><a name="обработка-ошибок-1062"></a>1062</h3>
+ **Сообщение**: *Неверное значение заголовка 'Accept'. Поддерживается только значение 'application/json;charset=utf-8'*
+ **Описание** Заголовок *Accept* должен отсутствовать либо иметь значение указанное в тексте ошибки.

<h3><a name="обработка-ошибок-1065"></a>1065</h3>
+ **Сообщение**: *Ошибка сохранения объекта: объект уже изменен/удален в параллельном запросе*
+ **Описание** Ошибка возникает при попытке изменить объект из нескольких параллельных запросов к API.

<h3><a name="обработка-ошибок-1070"></a>1070</h3>
+ **Сообщение**: *Ошибка: ваш тарифный план не позволяет вам работать с данным ресурсом*
+ **Описание** На вашем тарифном плане работа с указанным ресурсом недоступна.

<h3><a name="обработка-ошибок-1071"></a>1071</h3>
+ **Сообщение**: *Превышено ограничение на количество попыток регистрации*
+ **Описание** Вы попытались зарегистрироваться слишком много раз

<h3><a name="обработка-ошибок-1072"></a>1072</h3>
+ **Сообщение**: *Превышено ограничение на количество регистраций с указанного адреса*
+ **Описание** Вы попытались зарегистрироваться слишком много раз

<h3><a name="обработка-ошибок-1073"></a>1073</h3>
+ **Сообщение**: *Превышено ограничение на одновременное количество запросов*
+ **Описание** От вас поступает слишком много параллельных запросов в единицу времени.

<h3><a name="обработка-ошибок-1074"></a>1074</h3>
+ **Сообщение**: *Сервис временно недоступен, ведутся технические работы*
+ **Описание** На сервере проводятся технические работы.

<h3><a name="обработка-ошибок-1999"></a>1999</h3>
+ **Сообщение**: *Неизвестная ошибка*
+ **Описание** Произошла непредвиденная ошибка. Пожалуйста, обратитесь в поддержку сервиса МойСклад подробно изложив условия при которых эта ошибка произошла.

<h2>Ошибки формата</h2>
<h3><a name="обработка-ошибок-2000"></a>2000</h3>
+ **Сообщение**: *Ошибка формата: отсутствует начало объекта*
+ **Описание**: В данном месте ожидалось начало объекта. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2001"></a>2001</h3>
+ **Сообщение**: *Ошибка формата: входящий запрос не соответствует формату JSON*
+ **Описание**: Данные должны быть отправлены в формате JSON. Если это так, а ошибка всё-таки возникает - попробуйте добавить Header `Content-Type` со значением `application/json`.

<h3><a name="обработка-ошибок-2002"></a>2002</h3>
+ **Сообщение**: *Ошибка формата: неименованное внутреннее поле типа массив*
+ **Описание**: Проверьте указали ли вы наименование поля типа массив. Возможно присутствуют лишние открывающиеся/закрывающиеся скобки в теле запроса.

<h3><a name="обработка-ошибок-2003"></a>2003</h3>
+ **Сообщение**: *Ошибка формата: неименованное внутреннее поле типа объект*
+ **Описание**: Проверьте указали ли вы наименование поля типа "объект". Возможно присутствуют лишние открывающиеся/закрывающиеся скобки в теле запроса.

<h3><a name="обработка-ошибок-2004"></a>2004</h3>
+ **Сообщение**: *Ошибка формата: вложенные массивы недопустимы*
+ **Описание**: В рамках JSON API не обрабатываются массивы массивов. Проверьте тело запроса на корректность.

<h3><a name="обработка-ошибок-2005"></a>2005</h3>
+ **Сообщение**: *Ошибка формата: входящий JSON должен начинаться либо с объекта, либо с массива*
+ **Описание**: Отсутствует открывающаяся фигурная/квадратная скобка в начале тела запроса.

<h3><a name="обработка-ошибок-2006"></a>2006</h3>
+ **Сообщение**: *Ошибка формата: слишком большая вложенность объектов*
+ **Описание**: Максимальная глубина вложенности в JSON API - 10. Скорректируйте тело запроса и убедитесь, что это ограничение не нарушается.

<h3><a name="обработка-ошибок-2007"></a>2007</h3>
+ **Сообщение**: *Ошибка формата: слишком большое число вложенных объектов*
+ **Описание**: В JSON API в массиве может содержаться не более 1000 объектов.

<h3><a name="обработка-ошибок-2008"></a>2008</h3>
+ **Сообщение**: *Ошибка формата: запрос на шаблон не должен содержать массив*
+ **Описание**: С помощью запроса по ресурсу `{entity_name}/new` можно создать только 1 шаблон. Передача массива значений не поддерживается.

<h3><a name="обработка-ошибок-2009"></a>2009</h3>
+ **Сообщение**: *Ошибка формата: запрос на создание/обновление одной сущности не должен содержать массив*
+ **Описание**: При обновлении отдельной сущности подразумевается, что в теле запроса будет передано её новое представление (одно). В теле запроса должен быть один корневой объект.

<h3><a name="обработка-ошибок-2010"></a>2010</h3>
+ **Сообщение**: *Ошибка формата: отсутствует href для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных отсутствует поле **href**. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2012"></a>2012</h3>
+ **Сообщение**: *Ошибка формата: неизвестный type для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных указан неизвестный тип. Проверьте тело запроса. Возможно вы указываете неверное ключевое слово для сущности. Проверьте документацию по данной сущности и убедитесь в правильности передаваемого **type**.

<h3><a name="обработка-ошибок-2013"></a>2013</h3>
+ **Сообщение**: *Ошибка формата: неправильное значение href для meta поля '{доп. сообщение}'*
+ **Описание**: Переданный **href** указывает на несуществующий объект. Убедитесь в корректности ссылки. Ошибка может быть в версии API, типе ресурса (entity/pos/report), ключевом слове сущности/(отчёта), id сущности.

<h3><a name="обработка-ошибок-2014"></a>2014</h3>
+ **Сообщение**: *Ошибка формата: отсутствует meta для поля '{имя поля}'*
+ **Описание**: Для полей типа метаданных (ссылок на другие связанные объекты) необходимо значение в виде объекта, содержащего **meta**.

<h3><a name="обработка-ошибок-2015"></a>2015</h3>
+ **Сообщение**: *Ошибка формата: отсутствует id для поля '{имя поля}'*
+ **Описание**: При передаче вложенных сущностей в виде полей необходимо указывать id этих сущностей.

<h3><a name="обработка-ошибок-2016"></a>2016</h3>
+ **Сообщение**: *Ошибка формата: значение поля '{имя поля}' не соответствует типу {тип поля}*
+ **Описание**: Для указанного поле передано значение неверного типа. Исправьте тело запроса.

<h3><a name="обработка-ошибок-2017"></a>2017</h3>
+ **Сообщение**: *Ошибка формата: неизвестная ошибка*
+ **Описание**: Не удалось однозначно классифицировать ошибку. Убедитесь что формат передаваемых вами данных соответствует требуемому. Посмотрите примеры запросов в документации по используемой вами сущности.

<h3><a name="обработка-ошибок-2018"></a>2018</h3>
+ **Сообщение**: *Ошибка формата: отсутствует поле <field> для meta <type>*
+ **Описание**: Вы не указали обязательное поле объекта **meta**.

<h3><a name="обработка-ошибок-2019"></a>2019</h3>
+ **Сообщение**: *Ошибка формата: Поле <field> не совпадает с указанным в href для meta <type>*
+ **Описание**: В объекте **meta** нет соответствия между указанным полем и информацией в ссылке (**href**). Проверьте, совпадают ли **id**, **idType** и **type** в объекте **meta** и в ссылке (**href**) **meta**.

<h3><a name="обработка-ошибок-2020"></a>2020</h3>
+ **Сообщение**: *Ошибка формата: href для meta <type> должен ссылаться на сущность, /entity/*
+ **Описание**: В ссылке (**href**) объекта **meta** можно ссылаться только на ресурсы из posap /entity/.

<h3><a name="обработка-ошибок-2025"></a>2025</h3>
+ **Сообщение**: *Ошибка формата: Ошибка формата: значение <заголовок|параметр|поле> '<наименование>' не соответствует формату даты '<формат даты>'*
+ **Описание**: Переданное значение даты не соответствует формату даты

<h2>Общие ошибки валидации</h2>
<h3><a name="обработка-ошибок-3000"></a>3000</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может быть пустым или отсутствовать*
+ **Описание**: Необходимое поле не может содержать пустого значения или отсутствовать. Все необходимые поля можно посмотреть в документации по сущности, с которой вы работаете, под заголовком "Атрибуты сущности". Такие поля помечены как `Необходимое`.

<h3><a name="обработка-ошибок-3001"></a>3001</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может быть изменено*
+ **Описание**: Вы пытаетесь изменить поле являющееся полем только для чтения. Все read-only поля можно посмотреть в документации по сущности, с которой вы работаете, под заголовком "Атрибуты сущности". Такие поля помечены как `Только для чтения`.

<h3><a name="обработка-ошибок-3002"></a>3002</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может иметь отрицательное значение*
+ **Описание**: Данное поле принимает только числовые значения больше либо равные нулю.

<h3><a name="обработка-ошибок-3003"></a>3003</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' должно быть больше нуля*
+ **Описание**: Данное поле принимает только числовые значения больше нуля.

<h3><a name="обработка-ошибок-3004"></a>3004</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не соответствует полю связанного объекта*
+ **Описание**: Поле возврата не соответствует полю документа-основания. Невозможно изменить значения полей `agent, currency, vatIncluded` в возвратах на несоответствующие значениям этих же полей в документе-основании.

<h3><a name="обработка-ошибок-3005"></a>3005</h3>
+ **Сообщение**: *Ошибка сохранения объекта: неверное значение '{значение}' поля '{имя поля}'. Допустимые значения: {список значений}*
+ **Описание**: Вы пытаетесь присвоить несуществующее значение полю типа "перечисление"(enum). Проверить все возможные значения этого поля вы можете в документации по данной сущности в разделе "Атрибуты сущности".

<h3><a name="обработка-ошибок-3006"></a>3006</h3>
+ **Сообщение**: *Ошибка сохранения объекта: нарушено ограничение уникальности параметра '{имя параметра}'*
+ **Описание**: У указанного поля/параметра должно быть уникальное значение в системе. Например, если включена проверка на уникальность номеров операций, **name** у разных документов не может быть одинаковым.

<h3><a name="обработка-ошибок-3007"></a>3007</h3>
+ **Сообщение**: *Ошибка валидации сохраняемого объекта: '{объект}'*
+ **Описание**: Ошибка при обмене. Проверьте, соблюдает ли все условия передаваемый вами объект.

<h3><a name="обработка-ошибок-3008"></a>3008</h3>
+ **Сообщение**: *Ошибка сохранения объекта: значение поля '{имя поля}' превышает максимально допустимое значение*
+ **Описание**: Значение числового поля превышает максимально допустимое значение: 9 999 999 999.

<h3><a name="обработка-ошибок-3011"></a>3011</h3>
+ **Сообщение**: *Ошибка валидации штрихкода: невозможно добавить к сущности штрихкод длиной более 255 символов*
+ **Описание**: Исправьте длину штрихкода и попробуйте повторить запрос.

<h2>Точки продаж</h2>
<h3><a name="обработка-ошибок-4000"></a>4000</h3>
+ **Сообщение**: *Указанная точка продаж не активна*
+ **Описание**: Для выполнения операции необходимо активировать точку продаж.

<h2>Розничные смены (POS)</h2>
<h3><a name="обработка-ошибок-12003"></a>12003</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: розничная смена находится в корзине*
+ **Описание**: Смена с указанным id находится в корзине. Проверьте правильность указанного вами id смены.

<h3><a name="обработка-ошибок-12006"></a>12006</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: параметр 'retailShift' отсутствует или имеет неверный формат*
+ **Описание**: Убедитесь в наличии параметра **retailShift**.

<h3><a name="обработка-ошибок-12007"></a>12007</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: параметр 'retailShift' отсутствует или имеет неверный формат*
+ **Описание**: В теле запроса должно присутствовать поле **retailShift** (в camel-case) типа объект, содержащее в себе meta с ссылкой, содержащей **syncId** открываемой смены.

<h3><a name="обработка-ошибок-12008"></a>12008</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: параметр 'name' отсутствует*
+ **Описание**: В теле запроса должно присутствовать поле **name** (номер смены) типа строка.

<h3><a name="обработка-ошибок-12009"></a>12009</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: параметр 'openmoment' отсутствует*
+ **Описание**: В теле запроса должно присутствовать поле **openmoment** (дата-время открытия) типа строка в формате дата-время.

<h3><a name="обработка-ошибок-12010"></a>12010</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: параметр 'closemoment' отсутствует*
+ **Описание**: В теле запроса должно присутствовать поле **closemoment** (дата-время закрытия) типа строка в формате дата-время.

<h3><a name="обработка-ошибок-12012"></a>12012</h3>
+ **Сообщение**: *Розничная смена не существует*
+ **Описание**: Смена которую вы пытаетесь закрыть не существует. Убедитесь что указываете верный **syncId** смены.

<h3><a name="обработка-ошибок-12013"></a>12013</h3>
+ **Сообщение**: *Ошибка аутентификации. Пользователь {user} не является кассиром на точке продаж «{retailstore}»*
+ **Описание**: Для указанной точки продаж пользователь не является кассиром. Указать кассира можно в настройках точки продаж.

<h3><a name="обработка-ошибок-12014"></a>12014</h3>
+ **Сообщение**: *Непредвиденная ошибка сохранения токена*
+ **Описание**: Попробуйте осуществить запрос на получение токена ещё раз.

<h3><a name="обработка-ошибок-12015"></a>12015</h3>
+ **Сообщение**: *Ошибка получения токена: не найдена точка продаж*
+ **Описание**: Не найдено точки продаж с указанным id.

<h3><a name="обработка-ошибок-12016"></a>12016</h3>
+ **Сообщение**: *Пользователь-кассир деактивирован. Обратитесь к администратору аккаунта.*
+ **Описание**: Вы пытаетесь аутентифицироваться как неактивный пользователь. Следует обратиться к администратору аккаунта.

<h3><a name="обработка-ошибок-12017"></a>12017</h3>
+ **Сообщение**: *Неправильный или просроченный ключ доступа*
+ **Описание**: Срок действия ключа доступа истёк или же сам переданный ключ не корректен. Уточните вводимые данные.

<h3><a name="обработка-ошибок-12018"></a>12018</h3>
+ **Сообщение**: *Допустимо использование сессии только для авторизованной точки продаж*
+ **Описание**: Точка продаж должна быть привязана к токену. О том как это сделать вы можете прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).

<h3><a name="обработка-ошибок-12021"></a>12021</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: нельзя закрыть смену другой точки продаж*
+ **Описание**: Смена, которую вы пытаетесь закрыть, принадлежит другой точке продаж. Убедитесь в правильности token, который вы используете для аутентификации, а также в правильности **syncId** смены.

<h3><a name="обработка-ошибок-12022"></a>12022</h3>
+ **Сообщение**: *Указанный пользователь не является кассиром ни на одной точке продаж*
+ **Описание**: Только кассир на активной точке продаж может привязать точку продаж и получить токен. Указать кассира можно в настройках точки продаж.

<h3><a name="обработка-ошибок-12023"></a>12023</h3>
+ **Сообщение**: *Нельзя создать документ в рамках розничной смены, находящейся в корзине*
+ **Описание**: Смена с указанным id находится в корзине. Проверьте правильность указанного вами id смены.

<h3><a name="обработка-ошибок-12024"></a>12024</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: непредвиденная ошибка создания (входящего платежа|ПКО)*
+ **Описание** Ошибка в процессе создания входящего платежа или ПКО во время закрытия розничной смены.

<h3><a name="обработка-ошибок-12025"></a>12025</h3>
+ **Сообщение**: *Ошибка аутентификации: Неправильный пароль или имя пользователя*
+ **Описание** Ошибка в процессе аутентификации.

<h2>Товары</h2>
<h3><a name="обработка-ошибок-16000"></a>16000</h3>
+ **Сообщение**: *Ошибка сохранения товара: свойства алкогольной продукции не могут быть отрицательными*
+ **Описание**: Алкогольные поля "код алкогольной продукции", "крепость" и "объём" должны принимать значение строго большее 0.

<h3><a name="обработка-ошибок-16001"></a>16001</h3>
+ **Сообщение**: *Ошибка сохранения товара: весовой товар не может использовать учет по серийным номерам*
+ **Описание**: Товар не может одновременно быть весовым и использовать учёт по серийным номерам. Это - взаимоисключающие признаки.

<h3><a name="обработка-ошибок-16002"></a>16002</h3>
+ **Сообщение**: *Ошибка сохранения товара: нельзя отключить серийный учёт*
+ **Описание**: Если серийный учет однажды включен, то его уже нельзя отключить. В ином случае вы можете создать новый товар.

<h3><a name="обработка-ошибок-16003"></a>16003</h3>
+ **Сообщение**: *Ошибка сохранения товара: у изображения отсутствует контент*
+ **Описание**: При передаче изображение в составе товара в запросе на создание товара необходимо указывать поле **content**

<h3><a name="обработка-ошибок-16004"></a>16004</h3>
+ **Сообщение**: *Ошибка сохранения товара: невозможно преобразовать поле content в изображение*
+ **Описание**: Содержимым поля **content** должно быть изображение закодированное в формате base64 с расширением jpg или png.

<h3><a name="обработка-ошибок-16005"></a>16005</h3>
+ **Сообщение**: *Ошибка сохранения товара: Недостаточно места в хранилище.*
+ **Описание**: Место в хранилище, выделенное для вашей учётной записи закончилось.

<h3><a name="обработка-ошибок-16006"></a>16006</h3>
+ **Сообщение**: *Ошибка сохранения товара: размер изображения превышает максимально допустимый(3 мб)*
+ **Описание**: Попробуйте уменьшить размер изображения.

<h3><a name="обработка-ошибок-16008"></a>16008</h3>
+ **Сообщение**: *Ошибка сохранения товара: для использования упаковок нужно указать единицу измерения товара*
+ **Описание**: Для использования упаковок должна быть задана единица измерения товара

<h2>Документы</h2>
<h3><a name="обработка-ошибок-17002"></a>17002</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: серийный номер не может быть пустым*
+ **Описание**: Серийный номер не может быть пустой строкой.

<h3><a name="обработка-ошибок-17003"></a>17003</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: количество зарезрвированных товаров не может превышать общее количество*
+ **Описание**: Количество зарезервированного товара позиции документа не может превышать общее количество товара по документу.

<h3><a name="обработка-ошибок-17004"></a>17004</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: количество товаров в ожидании не может превышать общее количество*
+ **Описание**: Количество ожидаемого товара позиции документа не может превышать общее количество товара по документу.

<h3><a name="обработка-ошибок-17005"></a>17005</h3>
+ **Сообщение**: *Ошибка сохранения связанного документа: отсутствует ссылка на документ-основание*
+ **Описание**: При сохранении связанного документа необходима ссылка на документ-основание (например при сохранении возврата необходима ссылка на продажу).

<h3><a name="обработка-ошибок-17007"></a>17007</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: НДС не может быть больше 100*
+ **Описание**: Процент НДС может принимать значения от 0 до 100.

<h3><a name="обработка-ошибок-17008"></a>17008</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: скидка не может быть больше 100*
+ **Описание**: Процент скидки может принимать значения от 0 до 100.

<h3><a name="обработка-ошибок-17017"></a>17017</h3>
+ **Сообщение**: *Ошибка сохранения документа: количество переданных серийных номеров не соответствует количеству в позиции*
+ **Описание**: Поле позиции **quantity** должно соответствовать размеру коллекции **sn**.

<h2>Продажи</h2>
<h3><a name="обработка-ошибок-18000"></a>18000</h3>
+ **Сообщение**: *Ошибка сохранения продажи: сумма 'cashSum', 'noCashSum', 'qrSum', 'prepaymentCashSum', 'prepaymentNoCashSum' и 'prepaymentQrSum' не соответствует сумме по документу*
+ **Описание**: Сумма полей **cashSum**, **noCashSum**, **qrSum**,  **prepaymentCashSum**,  **prepaymentNoCashSum**,  **prepaymentQrSum** должна быть равна значению поля **sum** или отличаться менее чем на 10 единиц. В случае создания документа и указании вышеупомянутых полей в теле запроса, ответственность за подсчёт **sum** ложится на пользователя. **sum** считается как общая сумма по всем позициям документа. Допускается расхождение на 10 (учет идёт в копейках).

<h3><a name="обработка-ошибок-18003"></a>18003</h3>
+ **Сообщение**: *Ошибка сохранения продажи: нельзя указывать баллы к начислению или списанию без указания бонусной программы*
+ **Описание**: При заполнении любого из полей **bonusValueToEarn**, **bonusValueToSpend**, поле **bonusProgram** становится обязательным для заполнения.

<h3><a name="обработка-ошибок-18005"></a>18005</h3>
+ **Сообщение**: *В случае заполненного поля 'qrSum' поля 'cashSum' и 'noCashSum' должны быть пустыми*
+ **Описание**: *Смешанная оплата по QR-коду и карте или по QR-коду и наличными запрещена*

<h2>Серийные номера</h2>
<h3><a name="обработка-ошибок-45000"></a>45000</h3>
+ **Сообщение**: *Ошибка формата: количество переданных серийных номеров не соответствует количеству в позиции*
+ **Описание**: Поле позиции **quantity** должно соответствовать размеру коллекции **sn**.

<h3><a name="обработка-ошибок-45001"></a>45001</h3>
+ **Сообщение**: *Ошибка формата: указаны серийные номера для позиции {id}, по которой не ведётся серийный учет*
+ **Описание**: Для указанной позиции нельзя вести учет по товарам и передавать коллекцию **sn** для расчета.

<h3><a name="обработка-ошибок-46000"></a>46000</h3>
+ **Сообщение**: *Ошибка вызова внешней системы лояльности*
+ **Описание**: При вызове внешней системы лояльности возникла ошибка.

<h3><a name="обработка-ошибок-46001"></a>46001</h3>
+ **Сообщение**: *Отсутствует syncid для сущности 'counterparty'*
+ **Описание**: В данном методе предполагается, что у сущности **counterparty** должно быть непустое свойство **syncid**

<h3><a name="обработка-ошибок-46002"></a>46002</h3>
+ **Сообщение**: *Невозможно рассчитать чек*
+ **Описание**: Во время работы метода возникла ошибка, которая не позволяет выполнить пересчет. Может возникать, как последствие ошибки при вызове внешней системы (системы лояльности)

<h2>Тарифные ограничения</h2>
<h3><a name="обработка-ошибок-47000"></a>47000</h3>
+ **Сообщение**: *Тарифное ограничение: {описание ограничения}*
+ **Описание**: Сработало тарифное ограничение для текущего тарифа.

<h2>Предоплаты</h2>
<h3><a name="обработка-ошибок-48000"></a>48000</h3>
+ **Сообщение**: *Сумма предоплаты должна быть положительным числом.*
+ **Описание**: Сумма предоплаты складывается из полей **cashSum** и **noCashSum**. Проверьте, чтобы сумма этих полей была > 0.

<h3><a name="обработка-ошибок-48001"></a>48001</h3>
+ **Сообщение**: *В предоплате должна быть хотя бы одна позиция.*
+ **Описание**: Невозможно создать предоплату без позиций.

<h3><a name="обработка-ошибок-48002"></a>48002</h3>
+ **Сообщение**: *Сумма предоплаты не может превышать сумму по позициям*
+ **Описание**: Сумма предоплаты не может быть больше суммарной стоимости всех позиций.

<h3><a name="обработка-ошибок-48003"></a>48003</h3>
+ **Сообщение**: *Невозможно создать предоплату от розничного покупателя. Должен быть выбран "реальный" контрагент.*
+ **Описание**: Предоплата не может быть создана на контрагента "Розничный покупатель".

<h3><a name="обработка-ошибок-48004"></a>48004</h3>
+ **Сообщение**: *Невозможно создать предоплату по заказу с неположительной суммой*
+ **Описание**: Сумма заказа, по которой создаётся предоплата, должна быть >= 0.

<h3><a name="обработка-ошибок-48005"></a>48005</h3>
+ **Сообщение**: *Невозможно создать предоплату по заказу у которого нет хотя бы одной позиции*
+ **Описание**: В заказе, по которому создаётся предоплата, должна быть хотя бы одна позиция.

<h3><a name="обработка-ошибок-48006"></a>48006</h3>
+ **Сообщение**: *Невозможно создать предоплату по полностью оплаченному заказу*
+ **Описание**: Сумма платежей и предоплат по переданному заказу >= сумме самого заказа. Предоплата по такому заказу не имеет смысла.


<h2>Возвраты предоплат</h2>
<h3><a name="обработка-ошибок-49000"></a>49000</h3>
+ **Сообщение**: *Сумма возврата предоплаты должна быть положительным числом.*
+ **Описание**: Сумма возврата предоплаты складывается из полей **cashSum** и **noCashSum**. Проверьте, чтобы сумма этих полей была > 0.

<h3><a name="обработка-ошибок-49001"></a>49001</h3>
+ **Сообщение**: *В возврате предоплаты должна быть хотя бы одна позиция.*
+ **Описание**: Невозможно создать возврат предоплаты без позиций.


<h3><a name="обработка-ошибок-49002"></a>49002</h3>
+ **Сообщение**: *Сумма возврата предоплаты не может превышать сумму по позициям*
+ **Описание**: Сумма возврата предоплаты не может быть больше суммарной стоимости всех позиций.


<h3><a name="обработка-ошибок-49003"></a>49003</h3>
+ **Сообщение**: *Невозможно сохранить возврат предоплаты: сумма возвратов превышает сумму предоплаты.*
+ **Описание**: Невозможно сохранить возврат предоплаты, т.к. в противном случае сумма возвратов превысит сумму предоплаты.
