# group pos_data Подарочные сертификаты
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Покупатели [/giftcard]
### Получить подарочный сертификат [GET]
Запрос на получение подарочного сертификата.

### Параметры запроса
+ **name** - Номер сертификата

### Атрибуты ответа:
+ **name** - Номер сертификата `Необходимое`
+ **expireDate** - Дата, до которой действует сертификат в формате YYYY-MM-DD HH:mm:ss в UTC
+ **status** - Статус сертификата `Необходимое`
`[CAN_BE_USED, INVALID]`.
+ **currentBalance** - Сколько денег осталось на балансе сертификата в копейках
+ **initialBalance** - Начальная сумма сертификата в копейках
+ **meta** - Внешний уникальный идентификатор в формате метаданных (мета с syncId) `Необходимое`
+ **bonusProgram** - Метаданные об активной бонусной программе

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление подарочного сертификата.
  + Body
        <!-- include(body/giftcard/get.json) -->
