# group pos_general Основная информация

## Замечания по разработке клиентских приложений
При разработке клиентского приложения необходимо учитывать следующие моменты:
  + Структура ответов и типы полей поддерживаются нами неизменными
  + Может быть добавлено новое поле без нарушения структуры ответа
  + Может быть добавлен новый ресурс

## Ограничения
Для POS API установлены следующие ограничения:
  + Не более 100 запросов за 5 секундный период
  + Не более 5 параллельных запросов от одного пользователя
  + Не более 15 параллельных запросов от аккаунта
  + Не более 500 параллельных запросов с одного ip-адреса
  + Не более 10 Мб данных в одном запросе, отправляемом на сервер

## Обмен информацией
<h3>Получение информации</h3>
В рамках POS API вы можете:<br>
Запрашивать следующие сущности:
+ [Настройки точки продаж](#pos_data-настройки-точки-продаж)
+ [Настройки компании](#pos_data-настройки-компании)
+ [Скидки](#pos_data-скидки)
+ [Товары и услуги](#pos_data-скидки)
+ [Папки](#pos_data-папки)
+ [Покупатели](#pos_data-покупатели)
+ [Заказы покупателей](#pos_data-заказы-покупателей)

При запросе сущности в ответ от сервера приходит JSON представление сущности со всеми необходимыми для работы с ней в рознице полями.

<h3>Создание объектов</h3>
Также, в рамках POS API можно создавать следующие сущности:
+ [Товары](#pos_stuff-создание-товаров)
+ [Контрагенты](#pos_stuff-создание-контрагентов)
+ [Продажи](#pos_doc-продажи)
+ [Возвраты](#pos_doc-возвраты)
+ [Внесения денег](#pos_doc-внесение-денег)
+ [Выплаты денег](#pos_doc-выплата-денег)
+ [Предоплаты](#pos_doc-предоплаты)
+ [Возвраты предоплат](#pos_doc-возвраты-предоплат)

При успешном создании сервер вернет пустое тело ответа с HTTP кодом 201.

<h3>Операции со сменами</h3>
Также доступны 2 операции со сменами:
+ [Открытие](#pos_doc-операции-со-сменами-открыть-смену-put)
+ [Закрытие](#pos_doc-операции-со-сменами-закрыть-смену-put)

При успешной операции со сменой сервер вернёт пустое тело ответа с HTTP кодом 204.

<h3>Обновление сущностей</h3>
Розничный API сервиса МойСклад не поддерживает операции обновления сущностей.

<h3>Удаление сущностей</h3>
Розничный API сервиса МойСклад не поддерживает операции удаления сущностей.

## Обработка ошибок
<h3>СТРУКТУРА ОШИБОК</h3>
Ошибка в данном API представляет собой массив **errors**, содержащий объекты **error**, каждый из которых описывает отдельную ошибку.
<h3>СТРУКТУРА ОБЪЕКТА error</h3>
+ **error** - Заголовок ошибки
+ **parameter** - Параметр, на котором произошла ошибка
+ **code** - Код ошибки (Если поле отсутствует, смотрите HTTP status code)
+ **error_message**  - Сообщение, прилагаемое к ошибке.

<h3>Возвращаемые HTTP статусы ошибок и их значения:</h3>
| HTTP status code | Значение                                                                                |
| :--------------: |:----------------------------------------------------------------------------------------|
| 301              | Запрашиваемый ресурс находится по другому URL.                                          |
| 400              | Ошибка в структуре JSON передаваемого запроса                                           |
| 401              | Имя и/или пароль пользователя указаны неверно или заблокированы пользователь или аккаунт|
| 403              | У вас нет прав на просмотр данного объекта                                              |
| 404              | Запрошенный ресурс не существует                                                        |
| 405              | http-метод указан неверно для запрошенного ресурса                                      |
| 409              | Указанный объект используется и не может быть удалён                                    |
| 410              | Версия API больше не поддерживается                                                     |
| 412              | Не указан обязательный параметр строки запроса или поле структуры JSON                  |
| 413              | Размер запроса или количество элементов запроса превышает лимит                         |
| 429              | Превышен лимит количества запросов                                                      |
| 500              | При обработке запроса возникла непредвиденная ошибка                                    |
| 502              | Сервис временно недоступен                                                              |
| 503              | Сервис временно отключен                                                                |
| 504              | Превышен таймаут обращения к сервису, повторите попытку позднее                         |

Также, вместе с телом ответа ошибки, вам могут прийти следующие заголовки (Headers):
+ X-Lognex-Auth - расширенный код ошибки аутентификации
+ X-Lognex-Auth-Message - сообщение об ошибке.
+ X-Lognex-API-Version-Deprecated - дата отключения запрошенной версии API.
+ Location - URL по которому доступен запрашиваемый ресурс (в случае ответа с кодом 301)

<h4>Вы можете узнать лимит оставшихся запросов с помощью следующих заголовков</h4>
+ X-RateLimit-Limit - количество запросов, которые равномерно можно сделать в течение интервала до появления 429 ошибки
+ X-Lognex-Retry-TimeInterval - интервал в миллисекундах, в течение которого можно сделать эти запросы
+ X-RateLimit-Remaining - Число запросов, которые можно отправить до получения 429 ошибки
+ X-Lognex-Reset - время до сброса ограничения в миллисекундах. Равно нулю, если ограничение не установлено
+ X-Lognex-Retry-After - время до сброса ограничения в миллисекундах.

<h2>Все коды ошибок и их описания</h2>
___
<span class="scrlable">
<!-- include(errors.apib) -->
</span>
___

## Метаданные
Структура метаданных в posap:
<h3>Метаданные коллекций:</h3>
+  **href** - ссылка
+  **mediaType** - MIME тип
+  **size** - размер выборки
+  **limit** - макс. количество объектов в выборке
+  **offsetId** - id элемента, после которого начинается текущая страница сущностей
+  **direction** - направление листания. Одно из значений `[forward, backward]`
+  **previousHref** - Ссылка на предыдущую страницу (отображается только когда указан offsetId не по умолчанию)
+  **nextHref** - Ссылка на следующую страницу (отображается только когда указан offsetId не по умолчанию)

<h3>Метаданные объектов</h3>
+  **href** - ссылка на сущность
+  **mediaType** - MIME тип
+  **type** - тип сущности
+  **id** - id сущности
+  **idType** - тип id. Одно из значений `[native, sync]`

## Формат даты и времени в миллисекундах
В POS API можно получать поля типа дата-время (момент времени) в формате: `ГГГГ-ММ-ДД ЧЧ:ММ:СС.ммм`. Для этого нужно добавить специальный заголовок к запросу:<br>
`X-Lognex-Format-Millisecond` со значением `true`.

## Вывод JSON с отступами
В POS API можно получать ответы от сервера в виде pretty-print JSON (JSON с отступами вместо JSON в одну строку). Для этого нужно добавить специальный заголовок к запросу:<br>
`Lognex-Pretty-Print-JSON` со значением `true`.

## Заголовок временного отключения Веб-хуков
Через JSON API или POS API при запросах можно отключить уведомления вебхуков в контексте данного запроса.<br>
Для этого нужно указать заголовок `X-Lognex-WebHook-Disable` с произвольным значением.

## Стандартный розничный покупатель
На учётной записи пользователя есть контрагент, использующийся как контрагент для розничных продаж. По умолчанию он назван "Розничный покупатель". Если через POS API создать продажу, не указывая при этом поле **agent**, контрагентом такой продажи автоматически станет "Розничный покупатель".

<!-- include(scenario.apib) -->
<!-- include(retailstore_pos.apib) -->
<!-- include(token.apib) -->
<!-- include(retails_store_pos_solo.apib) -->
<!-- include(companysettings.apib) -->
<!-- include(discount_pos.apib) -->
<!-- include(assortment_pos.apib) -->
<!-- include(productfolder_pos.apib) -->
<!-- include(counterparty_pos.apib) -->
<!-- include(customerorder_pos.apib) -->
<!-- include(sn.apib) -->
<!-- include(retail_shift_ops.apib) -->
<!-- include(pos_retaildemand_recalc.apib) -->
<!-- include(pos_retaildemand.apib) -->
<!-- include(pos_retailsalesreturn.apib) -->
<!-- include(retaildrawercashin.apib) -->
<!-- include(retaildrawercashout.apib) -->
<!-- include(prepayment.apib) -->
<!-- include(prepaymentreturn.apib) -->
<!-- include(customerorder_pos.apib) -->
<!-- include(retailoperation.apib) -->
<!-- include(retaildemand_fiscalization.apib) -->
<!-- include(retailsalesreturn_fiscalization.apib) -->
<!-- include(prepayment_fiscalization.apib) -->
<!-- include(prepaymentreturn_fiscalization.apib) -->
<!-- include(minion_status.apib) -->
<!-- include(master_poll.apib) -->
<!-- include(master_approve.apib) -->
<!-- include(master_reject.apib) -->
<!-- include(retailstore_status_pos.apib) -->
<!-- include(product_pos.apib) -->
<!-- include(pos_counterparty_create.apib) -->
