# group pos_stuff Создание контрагентов
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Создание контрагента [/entity/counterparty]
### Создать Покупателя [POST]
Запрос на создание нового контрагента.
### Атрибуты запроса:
+ **meta** -внешний уникальный идентификатор в формате метаданных (мета с syncId) `Необходимое`
+ **name** - Имя Контрагента `Необходимое`
+ **discountCardNumber** - Номер дисконтной карты
+ **phone** - Номер городского телефона
+ **email** - Адрес электронной почты
+ **description** - Комментарий
+ **legalFirstName** - Имя контрагента
+ **legalMiddleName** - Отчество контрагента
+ **legalLastName** - Фамилия контрагента
+ **sex** - Пол контрагента
`[Мужской, Женский]`.

| Пол контрагента                | Значение поля sex          |
| ------------------------------ |:---------------------------|
| Мужской                        | MALE                       |
| Женский                        | FEMALE                     |

+ **birthDate** - Дата рождения контрагента


+ Request Пример (application/json)
Пример body запроса для создания нового контрагента.
  + Headers
      Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
      Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/pos_counterparty/post_request.json) -->

+ Response 201
  + Body
        <!-- include(body/pos_counterparty/post_response.json) -->
