# group pos_doc Расчет скидок для продажи и возврата
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `
## Расчет скидок и бонусов [/rpc/retaildemand/recalc]
### Рассчитать скидки и бонусы для продажи [POST]
Запрос на расчет скидок и бонусов для новой розничной продажи.
<h2> Атрибуты запроса </h2>
+ **agent** - [метаданные](#header-метаданные) контрагента продажи
+ **transactionType** - тип операции с бонусными баллами: начисление(EARNING) или списание(SPENDING). `Необходимое`
+ **positions** - позиции розничной продажи/возврата `Необходимое`
  - **assortment** - [метаданные](#header-метаданные) товара/модификации/услуги/комплекта `Необходимое`
  - **quantity** — количество, должно быть больше нуля `Необходимое`
  - **price** - цена `Необходимое`
  - **sn** - `Для товаров` Массив серийных номеров. Необходимо указывать только при учёте товара по серийным номерам.
    * **meta** - `Общее` [метаданные](#header-метаданные) серийного номера товара `Необходимое`
  - **pack** - Упаковка
    * **id** - id сущности упаковки `Необходимое`
    * **name** - Название упаковки `Необходимое`
    * **quantity** - Количество товаров в упаковке `Необходимое`
    * **barcode** - Штрихкод упаковки
### Атрибуты ответа

### Атрибуты ответа:
+ **bonusProgram** - [метаданные](#header-метаданные) активной бонусной программы `Необходимое`
+ **receiptExtraInfo** - текст для вывода в чеке
+ **agentBonusBalance** - Баланс контрагента по активной бонусной программе ДО совершения операции `Необходимое`
+ **bonusValueToEarn** - Количество баллов которое будет начислено этой операцией `Необходимое`
+ **bonusValueToSpend** - Количество баллов которое будет списано этой операцией `Необходимое`
+ **chequeSumWithoutDiscount** - Сумма для уплаты без учета скидок `Необходимое`
+ **paidByDiscountWithoutBonus** - Сумма, оплаченная скидками, без учета бонусной программы `Необходимое`
+ **paidWithBonusPoints** - Сумма, оплаченная из бонусных баллов `Необходимое`
+ **valueToPay** - Сумма для уплаты с учетом скидок `Необходимое`
+ **positions** - позиции розничной продажи/возврата в порядке соответствующем запросу `Необходимое`
  - **quantity** — количество `Необходимое`
  - **price** - цена `Необходимое`
  - **discountedPrice** - цена после применения всех скидок `Необходимое`
  - **assortment** - даные товара/модификации/услуги/комплекта `Необходимое`
    * **meta** - `Общее` [метаданные](#header-метаданные) товара/модификации/услуги/комплекта `Необходимое`
    * **name** - `Общее` Наименование объекта `Необходимое`
    * **code** - `Общее` Код сущности
    * **barcodes** - `Общее` Массив штрихкодов сущности
    * **uom** - `Общее` Единица измерения товара (строка)
    * **vat** - `Общее` НДС
    * **article** - `Для товаров и комплектов` Артикул товара
    * **soldByWeight** - `Для товаров` Весовой товар
    * **isSerialTrackable** - `Для товаров` учёт по серийным номерам `Необходимое`
    * **tobacco** - `Для товаров` Табачная продукция. Не может быть указан вместе с **egaisIsAlcoholic**, **soldByWeight** и **isSerialtrackable**
    + **trackingType** - Тип маркируемой продукции
      + **NOT_TRACKED** - Без маркировки
      + **TOBACCO** - Тип маркировки "Табак"
      + **SHOES** - Тип маркировки "Обувь"
    + **tnved** - Код ТН ВЭД
    + **paymentItemType** - Признак предмета расчета
      + **GOOD** - Товар (Товар/Комплект)
      + **SERVICE** - Услуга (Услуга)
      + **EXCISABLE_GOOD** - Подакцизный товар (Товар/Комплект)
      + **WORK** - Работа (Услуга)
      + **PROVIDING_RID** - Предоставление РИД (Услуга)
      + **COMPOUND_PAYMENT_ITEM** - Составной предмет расчета (Товар/Комплект/Услуга)
      + **ANOTHER_PAYMENT_ITEM** - Иной предмет расчета (Товар/Комплект/Услуга)
    * **image** - `Для товаров и комплектов` Изображение товара (объект)
      - **href** - Ссылка на изображение
      - **miniature** - Ссылка на миниатюру изображения
      - **tiny** - Ссылка на уменьшенную версию изображения
    * **components** - `Для комплектов` Компоненты комплекта, это список товаров/услуг/модификаций, который входят в состав комплекта. Компонентов у комплекта может быть от 1 до 10. `Необходимое`
      - **meta** - Метаданные сущности `Необходимое`
      - **quantity** - количество компонентов в комплекте.
  - **sn** - `Для товаров` Массив серийных номеров. Необходимо указывать только при учёте товара по серийным номерам.
    * **meta** - [метаданные](#header-метаданные) серийного номера товара `Необходимое`
    * **name** - Наименование серийного номера
  - **pack** - Упаковка
    * **id** - id сущности упаковки `Необходимое`
    * **name** - Название упаковки `Необходимое`
    * **quantity** - Количество товаров в упаковке `Необходимое`
    * **barcode** - Штрихкод упаковки

+ Request Пример 1 (application/json)
Пример расчета для новой розничной продажи с начислением бонусов.
  + Headers
    Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
    Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/scenario/recalc_post_request.json) -->

+ Response 200
  + Body
        <!-- include(body/scenario/recalc_post_response.json) -->
