# group pos_cheque_rpc Создание предоплаты на фискализацию
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `
## Предоплата на фискализацию [/cheque/minion/entity/prepayment]

### Создать предоплату на фискализацию [POST]
Запрос на создание предоплаты и помещение ее в очередь облачных чеков на фискализацию.

<h2> Атрибуты запроса </h2>
Структура полностью соответствует обычному созданию предоплаты для эндпоинта entity/prepayment

+ Request Пример 1 (application/json)
Пример создания новой предоплаты.
  + Headers
    Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
    Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/prepayment/post_request.json) -->

+ Response 201
  + Body
        <!-- include(body/prepayment/post_response.json) -->