# group pos_doc Предоплаты
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `
## Предоплаты [/entity/prepayment]
### Создать предоплату [POST]
Запрос на создание новой предоплаты по заказу в рамках смены с указанным id.
<h2> Атрибуты запроса </h2>
+ **meta** - внешний уникальный идентификатор документа в формате метаданных (meta с syncId) `Необходимое`
+ **id** - id сущности в сервисе
+ **name** - Номер предоплаты `Необходимое`
+ **description** - Комментарий
+ **moment** - Дата и время предоплаты
+ **sum** - Итоговая сумма предоплаты. Равна сумме нал + безнал.
+ **agent** - Покупатель ссылка на контрагента в формате метаданных
+ **positions** - позиции предоплаты `Необходимое`
  - **assortment** - позиция документа, ссылка на товар/модификацию/услугу/комплект в формате метаданных `Необходимое`
  - **quantity** — количество реализуемого товара, должно быть положительным `Необходимое`
  - **price** - цена `Необходимое`
  - **discount** - процент скидки
  - **vat** - процент НДС
  - **vatEnabled** - включен ли НДС для позиции. С помощью этого флага для позиции можно выставлять НДС = 0 или НДС = "без НДС". (vat = 0, vatEnabled = false) -> vat = "без НДС", (vat = 0, vatEnabled = true) -> vat = 0%
+ **vatEnabled** - флаг, указывающий, что документ содержит НДС
+ **vatIncluded** - флаг, указывающий, включен ли НДС в цену (по умолчанию включен)
+ **vatIncluded** - Цена включает НДС
+ **vatSum** - Сумма НДС
+ **retailStore** - ссылка на точку продаж (meta с syncId).
+ **retailShift** - ссылка на смену (meta с syncId). `Необходимое`
+ **cashier** - ссылка на кассира в формате метаданных.
+ **customerOrder** - ссылка на заказ, по которому производится предоплата в формате метаданных. `Необходимое`
+ **cashSum**  - Оплачено наличными
+ **noCashSum** - Оплачено картой
+ **qrSum** - оплачено по QR-коду
+ **environment** - информация об окружении
  - **device** - информация об устройстве
  - **os** - информация об операционной системе
  - **software** - информация о ПО
    - **name** - наименование ПО `Необходимое при передаче software`
    - **vendor** - производитель
    - **version** - версия ПО
  - **chequePrinter** - данные о ККТ
    - **vendor** - производитель
    - **name** - наименование `Необходимое при передаче chequePrinter`
    - **serial** - серийный номер
    - **fiscalDataVersion** - формат фискальных данных
    - **driver** - информация об используемом драйвере
      - **name** - наименование драйвера
      - **version** - версия драйвера
    - **fiscalMemory** - информация о фискальном накопителе
      - **fiscalDataVersion** - версия фискальной памяти
    - **firmwareVersion** - Версия прошивки ККТ
  - **paymentTerminal** - информация о платежном терминале
    - **acquiringType** - информация о типе эквайера (например: inpas/payme)
+ **cheque** - информация о чеке
  - **fiscal** -  отметка о том, был ли использован ФР
  - **online** - признак электронного чека
  - **printed** - признак бумажного чека
  - **phone** - номер телефона, на который высылается электронный чек
  - **email** - адрес электронной почты, на который высылается электронный чек
  - **number** - номер чека
  - **sum** - сумма чека
  - **fnNumber** - номер ФН
  - **fiscalDocSign** - Фискальный признак документа
  - **fiscalDocNumber** - Номер фискального документа
  - **time** - время фискализации
+ **cardTransaction** - информация о транзакции в случае оплаты картой
  - **pan** - номер банковской карты
  - **transactionId** - id транзакции
  - **authCode** - inpas код аутентификации
  - **rrnCode** - Номер ссылки (RRN)
  - **amount** - сумма `Необходимое`
  - **acquiringType** - информация о типе эквайера (например: inpas/payme) `Необходимое`
  - **approvalNumber** - inpas/payme номер операции (код подтверждения)
  - **description** - комментарий
+ **qrTransaction** - информация о транзакции в случае оплаты по QR-коду
  - **transactionId** - id транзакции
  - **externalOperationId** - id заказа в системе банка
  - **authCode** - код авторизации транзакции
  - **acquiringType** - название API, через которое была проведена оплата
  - **merchantId** - id продавца при оплате по СБП через терминал Inpas
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

Если поле **vatEnabled**=**true**, а поле **vatIncluded**=**false**, то НДС не входит в цену и ее надо считать.

+ Request Пример 1 (application/json)
Пример создания новой предоплаты.
  + Headers
    Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
    Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/prepayment/post_request.json) -->

+ Response 201
  + Body
        <!-- include(body/prepayment/post_response.json) -->
