# Group pos_doc Операции со сменами
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `


## Открыть смену [/rpc/openshift/]
### Открыть смену [PUT]
Запрос на открытие смены, привязанной к точке продаж с указанным syncId и к указанному моменту времени.

<h2> Атрибуты запроса </h2>
+ **retailShift** - внешний уникальный идентификатор документа (meta с syncId). `Необходимое`
+ **name** - номер смены `Необходимое`
+ **openmoment** - дата открытия смены `Необходимое`
+ **cheque** - информация о смене
  - **start** - информация об открытии смены
    - **fnNumber** - номер ФН
    - **kktRegNumber** - регистрационный номер ККТ
    - **fiscalDocSign** - фискальный признак документа
    - **shiftNumber** - номер смены
    - **fiscalDocNumber** - номер фискального документа
    - **time** - дата и время открытия смены

+ Request Пример (application/json)
Пример запроса на открытие смены.
  + Headers
      Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
      Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/retail_shift/open_request.json) -->
+ Response 204
  + Body
        <!-- include(body/retail_shift/open_put.json) -->

## Закрыть смену [/rpc/closeshift/]
### Закрыть смену [PUT]
<h2> Атрибуты запроса </h2>
+ **retailShift** - внешний уникальный идентификатор документа (meta с syncId). Указанная смена должна существовать и быть открытой `Необходимое`
+ **closemoment** - дата закрытия смены `Необходимое`
+ **retailDrawerCashout** - внешний уникальный идентификатор выплаты (meta с syncId). Если присутствует ссылка на выплату, сумма выплаты больше 0 и в настройках точки продаж
стоит флаг "Создавать ПКО при закрытии смены", то при закрытии смены будет создаваться связанный ПКО.
+ **cheque** - информация о смене
  - **start** - информация об открытии смены
    - **fnNumber** - номер ФН
    - **kktRegNumber** - регистрационный номер ККТ
    - **fiscalDocSign** - фискальный признак документа
    - **shiftNumber** - номер смены
    - **fiscalDocNumber** - номер фискального документа
    - **time** - дата и время открытия смены
  - **end** - информация о закрытии смены
    - **fnNumber** - номер ФН
    - **kktRegNumber** - регистрационный номер ККТ
    - **fiscalDocSign** - фискальный признак документа
    - **shiftNumber** - номер смены
    - **fiscalDocNumber** - номер фискального документа
    - **chequesTotal** - количество чеков за смену
    - **fiscalDocsTotal** - количество фискальных документов за смену
    - **time** - дата и время закрытия смены

+ Request Пример (application/json)
Пример запроса на закрытие смены.
  + Headers
      Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
      Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/retail_shift/close_request.json) -->
+ Response 204
  + Body
        <!-- include(body/retail_shift/close_put.json) -->
