# group pos_begin Точка продаж
## Авторизация (BASIC)
Для данного ресурса предусмотрена обычная BASIC авторизация по паре логин-пароль.

## Точка продаж [/admin/retailstore]
### Получить точки продаж [GET]
Запрос на получение точек продаж, на которых пользователь является кассиром.

### Атрибуты объектов ответа
+ **meta** - Метаданные точки продаж `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
+ **version** - Версия сущности `Необходимое`
+ **updated** - Момент последнего обновления сущности `Необходимое`
+ **name** - Наименование точки продаж `Необходимое`
+ **description** - Описание точки продаж
+ **externalCode** - Внешний код точки продаж `Необходимое`
+ **address** - Адрес
+ **controlShippingStock** - Контроль остатков `Необходимое`
+ **onlyInStock** - Выгружать только товары в наличии. Доступно только при активном контроле остатков.
+ **controlCashierChoice** - Выбор продавца `Необходимое`
+ **discountEnable** - Разрешить ручные скидки `Необходимое`
+ **discountMaxPercent** - Максимально разрешенная скидка `Необходимое`
+ **priceType** - Тип цен, с которыми будут продаваться товары в рознице `Необходимое`
+ **authTokenAttached** - Флаг, указывающий, что для точки продаж уже был установлен токен обмена
(повторная установка токена может привести к тому, что данные с предыдущего устройства перестанут выгружаться) `Необходимое`
+ **cashiers** - Кассиры которые могут работать на точке продаж `Необходимое`. Выводится максимум 100 кассиров.
  - **meta** - метаданные
  - **uid** - идентификатор учетной записи кассира
  - **firstName** - Имя
  - **middleName** - Отчество
  - **lastName** - Фамилия
  - **pinCode** - ПИН-код
  - **image** - Фотография кассира
    - **href** - Ссылка на изображение
    - **miniature** - Ссылка на миниатюру изображения
    - **tiny** - Ссылка на уменьшенную версию изображения
  - **inn** - ИНН
  - **position** - Должность
  - **email** - Адрес электронной почты
+ **organization** - организация которой принадлежит точка продаж `Необходимое`
  - **meta** - метаданные `Необходимое`
  - **name** - Краткое наименование `Необходимое`
  - **companyType** - Тип организации `Необходимое`
  - **legalTitle**- Полное наименование
  - **legalAddress**- Юридический адрес
  - **actualAddress** - Фактический адрес
  - **inn** - ИНН
  - **kpp** - КПП
  - **ogrn** - ОГРН
  - **okpo** - ОКПО
  - **ogrnip** - ОГРНИП
  - **certificateNumber** - Номер свидетельства
  - **certificateDate** - Дата свидетельства
  - **email** - Адрес электронной почты
  - **phone** - Номер телефона
  - **fax** - факс
  - **isEgaisEnable** - ЕГАИС включен
  - **payerVat**- Плательщик НДС
  - **fsrarId** - Идентификатор в ФСРАР
  - **utmUrl** - Адрес и порт УТМ
+ **store** - склад с которого торгует точка продаж
  - **meta** - Метаданные
  - **name** - Наименование склада
  - **parent** - родительский склад
  - **pathName** - Группа, к которой относится склад `Необходимое`
  - **address** - Адрес `Необходимое`
+ **acquire** - Банк эквайер операций по карте
  - **meta** - Метаданные
+ **lastOperationNames** - коллекция номеров последних созданных документов на данной точке продаж. `Необходимое`
Каждый элемент коллекции - тип и имя
  - **entity** - тип документа `Необходимое`
  - **name** - Номер документа `Необходимое`
  - **moment** - Дата документа `Необходимое`
+ **egaisEnabled** - Точка продаж должна передавать данные в ЕГАИС `Необходимое`
+ **frNumber** - Номер модели ФР `Необходимое`
+ **returnFromClosedShiftEnabled** - Разрешить возвраты в закрытых сменах `Необходимое`
+ **alwaysPrintCheck** - Обязательная печать чеков `Необходимое`
+ **issueOrders** - Выдача заказов `Необходимое`
+ **sellReserves** - Учет резервов `Необходимое`
+ **ofdEnabled** - Отправлять электронный чек через ОФД `Необходимое`
+ **allowCustomPrice** - Разрешить продажу по свободной цене `Необходимое`
+ **cash** - Остаток денег в кассе `Необходимое`
+ **createPaymentInOnRetailShiftClosing** - Создавать входящий платеж при закрытии смен. Если флаг включен, в закрываемой смене
указан банк-эквайер и безналичная выручка за смену (с учетом комиссии) больше 0, то при закрытии смены будет создан входящий платеж `Необходимое`
+ **createCashInOnRetailShiftClosing** - Создавать ПКО при закрытии смены. Если флаг включен, в операции закрытия смены
есть ссылка на выплату и сумма выплаты больше 0, то при закрытии смены будет создан связанный ПКО `Необходимое`
+ **allowCreateProducts** - Разрешить создавать товары
+ **allowCreateReturnWithoutDemand** - Разрешить создание возвратов без основания
+ **isPhonePriority** - Приоритет отправки электронного чека на телефон. Если флаг выключен, приоритет отправки изменяется на email. Поле недоступно, если приоритет имеет значение Не отправлять или выключен флаг для отправки электронного чека через ОФД .
+ **isOnlineDiscount** - Возможность использовать скидку и рассчитывать чек на стороне сервера
+ **receiptTemplate** - Шаблон чека
  - **meta** - Метаданные шаблона чека
  - **header** - Верхний блок шаблона чека
  - **footer** - Нижний блок шаблона чека
+ **reservePrepaidGoods** - Резервировать товары за которые внесена предоплата
+ **environment** - информация об окружении
  - **device** - информация об устройстве
  - **os** - информация об операционной системе
  - **software** - информация о ПО
    + **name** - наименование ПО. `Необходимое`
    + **vendor** - Производитель.
    + **version** - версия ПО.
  - **chequePrinter** - данные о ККТ
    + **vendor** - Производитель
    + **name** - Наименование. `Необходимое`
    + **serial** - серийный номер
    + **fiscalDataVersion** - формат фискальных данных
    + **driver** - информация об используемом драйвере
      - **name** - наименования драйвера
      - **version** - Версия драйвера
    + **fiscalMemory** - информация о фискальном накопителе
      - **fiscalDataVersion** - версия фискальной памяти
    + **firmwareVersion** - Версия прошивки ККТ
  - **paymentTerminal** - информация о платежном терминале
    + **acquiringType** - информация о типе эквайера (например: inpas/payme)
+ **state** - информация о статусе точки продаж
  - **sync** - состояние синхронизации
    + **message** - состояние синхронизации.
    + **lastAttempMoment** - Дата последней сихронизации (не обязательно успешной). `Необходимое`
  - **lastCheckMoment** - дата и время последней синхронизации
  - **fiscalMemory** - информация о фискальной памяти
    + **error** - информация об ошибке ФН
      - **сode** - код ошибки ФН
      - **message** - описание ошибки
    + **notSendDocCount** - Количество неотправленных документов в ОФД
    + **notSendFirstDocMoment** - Дата первого документа в очереди на отправку
  - **paymentTerminal** - информация о платежном терминале `Deprecated`
    + **acquiringType** - информация о типе эквайера (например: inpas/payme)
+ **enableNotMRCTobaccoSale** - Разрешить продавать табачную продукцию не по МРЦ. `Deprecated`
+ **tobaccoMrcControlType** - Контроль МРЦ для табачной продукции
+ **markingSellingMode** - Продажа маркированных товаров
+ **qrPayEnabled** - возможность оплаты по QR-коду на точке продаж
+ **qrAcquire** - банк эквайер операций по QR-коду
  - **meta** - Метаданные
+ **isExternalCustomers** - Возможность искать покупателей во внешней системе лояльности
+ **sendMarksForCheck** - настройки для указания необходимости передавать коды маркировки для проверки с ККТ в мастер-кассу
+ **requiredFio** - Обязательность поля ФИО при создании контрагента
+ **requiredPhone** - Обязательность поля телефон при создании контрагента
+ **requiredEmail** - Обязательность поля эл. почта при создании контрагента
+ **requiredBirthdate** - Обязательность поля дата рождения при создании контрагента
+ **requiredSex** - Обязательность поля пол при создании контрагента
+ **requiredDiscountCardNumber** - Обязательность поля номер дисконтной карты при создании контрагента

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление точки продаж.
  + Body
        <!-- include(body/pos_retailstore/get.json) -->
