# group pos_doc Розничные операции
### Авторизация (token)
Для данного ресурса необходима авторизация по **token**. О том как получить данный token можно прочитать [тут](#pos_begin-привязка-точки,-получение-токена-получение-token).
Варианты аутентификации с помощью token:
  + С помощью заголовков (Header):
     **Lognex-Pos-Auth-Token** со значением токена, а также Header'ом **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира, от имени которого выполняется запрос. При этом Header **Authorization** НЕ указывается.
     * Пример:
      - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
      - `Lognex-Pos-Auth-Cashier-Uid:employee@company`
  + C помощью обычной BASIC авторизации с парой логин-пароль, где:
    - логин - uid кассира, от имени которого выполняется запрос
    - пароль - token точки продаж
      * Пример:
        - `Username: admin@myorg`
        - `Password: 9aa01067f9abc091ec6354fa73b5e05fda9e07fa`
  + С помощью cookie:
    - имя куки:  `Lognex-Pos-Auth`
    - значение: `<uid кассира>:<token точки продаж>`
      * Пример:
        - `name = Lognex-Pos-Auth`
        - `value = admin@myorg:4f2dc4d646bf0275de20b8f7f0b4f6fdda79cec0 `

## Розничные операции [/entity/retailoperation]
### Получить Розничные операции [GET]
Запрос на получение розничных операций.

### Атрибуты ответа:
#### Служебные
+ **meta** - Уникальный идентификатор в формате метаданных `Необходимое`
+ **id** - ID в формате UUID `Необходимое`
#### Основные данные
+ **name** - Имя `Необходимое`
+ **agent** - Ссылка на покупателя в формате метаданных
+ **sum** - Сумма операции
+ **noCashSum** - Оплачено картой
+ **qrSum** - оплачено по QR-коду
+ **moment** - Дата и время розничной операции
+ **retailShift** - Смена с датой открытия и закрытия
+ **prepaymentCash** - Предоплата наличными
+ **prepaymentNoCash** - Предоплата картой
+ **prepaymentQrSum** - предоплата по QR-коду
+ **returned** - Признак того, был ли сделан возврат
+ **masterShift** - Смена на которой была фискализирована операция с датой открытия и закрытия
+ **isCloud** - Признак того, что операция была фискализирована удаленно

#### Дополнительные данные продажи в списке операций
+ **prepaymentCash** - Предоплата наличными
+ **prepaymentNoCash** - Предоплата картой
+ **prepaymentQrSum** - предоплата по QR-коду

#### Данные, получаемые из запроса конкретного заказа
+ **name** - Имя `Необходимое`
+ **description** - Описание
+ **moment** - Дата `Необходимое`
+ **vatIncluded** - Включен ли НДС в цену `Необходимое`
+ **vatEnabled** - Учитывается ли НДС `Необходимое`
+ **deliveryPlannedMoment** - Планируемая дата отгрузки
+ **state** - Статус
+ **positions** - Ссылка на позиции в формате метаданных `Необходимое`
+ **agent** - Ссылка на покупателя в формате метаданных вместе с телефоном, именем и email `Необходимое`

#### Позиции Заказа покупателя
Позиции Заказа - это список товаров/услуг/модификаций/комплектов. Объект позиции Заказа содержит следующие поля:

+ **assortment** - Ссылка на товар/услугу/модификацию/комплект в формате метаданных, которую представляет собой позиция `Необходимое`
+ **quantity** - Количество товаров/услуг/модификаций/комплектов данного вида в позиции `Необходимое`
+ **price** - Цена товаров/услуг/модификаций/комплекта в копейках `Необходимое`
+ **vat** - НДС, которым облагается текущая позиция `Необходимое`
+ **discount** - Процент скидки или наценки `Необходимое`
+ **reserve** - Резерв данной позиции `Необходимое`
+ **sn** - список серийных номеров
   + **meta** - Метаданные о серийном номере
   + **name** - Имя

#### Ассортимент позиции
Ассортимент позиции - информация о товаре в позиции заказа Объект ассортимента содержит следующие поля:

+ **meta** - Метаданные, представляющие собой ссылку на объект
+ **name** - Наименование
+ **code** - Код
+ **article** - Артикул товара
+ **images** - Изображения товара в формате метаданных
+ **barcodes** - Массив штрихкодов
+ **uom** - Единица измерения
+ **soldByWeight** - Продажа по весу (только у товара)
+ **isSerialTrackable** - Учет по серийным номерам. Не может быть указан вместе с alcoholic и weighed (только у товара)
+ **salePrices** - Цены продажи (нет у серий)
+ **egaisIsAlcoholic** - отметка о том, является ли товар алкогольным (приходит только для товаров)
+ **label** - Имя серии (выводится только для серий)

#### Поля комплектов
+ **components** - Компоненты комплекта, это список товаров/услуг/модификаций, который входят в состав комплекта. Компонентов у комплекта может быть от 1 до 10 `Необходимое`
  + **meta** - Метаданные сущности `Необходимое`
  + **quantity** - Количество компонентов в комплекте. Выводятся в виде метаданных сущности.

### Фильтры
+ **search** - Поиск по номеру операции (вхождение поисковой строки, как подстроки имени операции), по сумме операции
(с точностью до знака после точки), по названию позиции (только одной) и по имени контрагента, если длина поискового запроса больше 2х символов. Тип значения - строка.
+ **dtype** - Поиск по типу операции (только по одному и в нижнем регистре). Тип значения - строка.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Заказов покупателей.
  + Body
        <!-- include(body/pos_retailoperation/get.json) -->