# group pos_stuff Обновить статус точки продаж
### Авторизация
Для данного ресурса предусмотрена авторизация по token. Все запросы к ресурсам справочника товаров  и услуг должны сопровождаться
HTTP заголовок **Lognex-Pos-Auth-Token** со значением токена, а также HTTP заголовком **Lognex-Pos-Auth-Cashier-Uid**, значением которого будет uid кассира,
от имени которого выполняется запрос. При этом заголовок **Authorization** НЕ указывается.
 + Пример:
  - `Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b`
  - `Lognex-Pos-Auth-Cashier-Uid:employee@company`

 О том как получить данный token можно прочитать [тут](#получение-token).
## Обновить статус точки продаж [/state]

### Обновить статус точки продаж [POST]
Запрос на обновление статуса точки продаж.

Если поле, помеченое как `Необходимое`, отсутствует в запросе на обновление статуса точки продаж, то все JSON поля данного объекта (включая поля дочерних объектов), в котором находится данное поле, устанавливаются в null

### Атрибуты запроса
+ **environment** - Информация об окружении
  - **device** - Информация об устройстве
  - **os** - Информация об операционной системе
  - **software** - Информация о ПО
    - **name** - Наименование ПО `Необходимое`
    - **vendor** - Производитель
    - **version** - Версия ПО
  - **chequePrinter** - Данные о ККТ
    - **vendor** - Производитель
    - **name** - Наименование ПО `Необходимое`
    - **fiscalDataVersion** - Формат фискальных данных
    - **driver** - Информация об используемом драйвере
      - **name** - Наименование драйвера
      - **version** - Версия драйвера
    - **fiscalMemory** - Информация о фискальном накопителе
      - **fiscalDataVersion** - Версия фискальной памяти
      - **fiscalValidityDate** - Срок действия ФН
    - **firmwareVersion** - Версия прошивки ККТ
    - **taxSystem** - Системы налогообложения, зарегистрированные в ККТ. Если в ККТ зарегистрировано несколько систем налогообложения, строка будет содержать все названия через запятую
    - **frDate** - Дата ККТ
  - **paymentTerminal** - информация о платежном терминале
    + **acquiringType** - информация о типе эквайера (например: inpas/payme)
+ **state** - Статус синхронизации
  - **sync** - Состояние синхронизации точки продаж
    - **message** - Информация о состоянии синхронизации
    - **lastAttemptMoment** - Дата последней синхронизации `Необходимое`
  - **fiscalMemory** - Состояние фискального накопителя
    - **error** - Информация об ошибке фискального накопителя
      - **code** - Код ошибки фискального накопителя
      - **message** - Описание ошибки
    - **notSendDocCount** - количество не отправленных в ОФД документов
    - **notSendFirstDocMoment** - Дата первого документа в очереди на отправку
  - **paymentTerminal** - информация о платежном терминале `Deprecated`
    - **acquiringType** - информация о типе эквайера (например: inpas/payme)


+ Request Пример (application/json)
Пример body запроса для обновления статуса точки продаж.
  + Headers
      Lognex-Pos-Auth-Token: 6ab89be1ae6ff147755625ee8da948e42612233b
      Lognex-Pos-Auth-Cashier-Uid:employee@company
  + Body
        <!-- include(body/retailstore_status_pos/post_request.json) -->

+ Response 204 (application/json)