# group pos_begin Привязка точки, получение токена
## Авторизация (BASIC)
Для данного ресурса предусмотрена обычная BASIC авторизация по паре логин-пароль с небольшим отличием от стандартного поведения - сервер вместе с кодом 401 не возвращает заголовок WWW-Authenticate после неудачной аутентификации.

## Получение Token [/admin/attach/{id}]
Данный ресурс предназначен для получения token для аутентификации на конкретной точке продаж.
Id точки продаж передаётся в параметрах запроса. Данный запрос могут выполнить только кассиры на данной точке продаж
и администраторы. Получить информацию о точках продаж можно воспользовавшись [этим ресурсом](#pos_begin-точки-продаж).
+ Если пользователь не является кассиром или администратором - в результате запроса произойдёт ошибка с кодом 403.
+ Если точка продаж с указанным id не найдена - возникнет ошибка с кодом 404.

После успешного запроса происходит создание токена обмена для данной точки продаж, который будет заменять связку логин-пароль при обращении к ресурсам розницы.
Все предыдущие токены для точки при этом аннулируются.



### Назначить токен для точки продаж [POST]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id точки продаж, которой назначается token

> Данный запрос приведёт к замене всех существующих токенов на данной точке продаж на новый.

Если пользователь является администратором либо кассиром на данной точке продаж и существует точка продаж
с id равным переданному - результатом запроса будет ответ от сервера с кодом 201
и телом, содержащим token для последующей аутентификации на данной точке продаж.

+ Response 201 (application/json)
Успешный запрос. Результат - токен для последующей аутентификации на данной точке продаж.
  + Body
        <!-- include(body/token/post.json) -->
